using System.Numerics;using DDVWF.Core.Zone;
namespace DDVWF.Sage.Wld;
public static class SageSkinnedSceneBuilder
{
 public static RenderMesh? Build(WldDocument doc,ReadOnlySpan<byte> source,SageSkeleton skeleton,string name)
 {
  var meshTargets=new List<(int MeshIndex,int BoneIndex)>();var lastBone=-1;
  foreach(var bone in skeleton.Bones){if(bone.MeshReferenceIndex<0||bone.MeshReferenceIndex>=doc.Fragments.Count)continue;var rf=doc.Fragments[bone.MeshReferenceIndex];if(rf.KnownType!=WldFragmentType.MeshReference)continue;var mi=WldMaterialReader.ReadReference(rf,source);if(mi>=0&&mi<doc.Fragments.Count&&doc.Fragments[mi].KnownType is WldFragmentType.Mesh or WldFragmentType.LegacyMesh){meshTargets.Add((mi,bone.Index));lastBone=bone.Index;}}
  if(meshTargets.Count==0)return null;
  var primitives=new List<RenderPrimitive>();
  foreach(var (mi,_) in meshTargets){var mesh=WldMeshReader.Read(doc,doc.Fragments[mi],source);var mats=WldMaterialReader.ReadMaterialList(doc,mesh.MaterialListIndex,source);var polygon=0;foreach(var group in mesh.MaterialGroups){var verts=new List<RenderVertex>();var idxs=new List<ushort>();for(var p=0;p<group.PolygonCount;p++){var poly=mesh.Polygons[polygon++];foreach(var vi in new[]{(int)poly.A,(int)poly.B,(int)poly.C}){var bone=lastBone>=0?lastBone:BoneFor(mesh,vi);var v=mesh.Vertices[vi];var n=mesh.Normals[vi];var uv=mesh.Uvs[vi];var pos=new Vector3(-(v.X+mesh.Center.X),v.Z+mesh.Center.Z,v.Y+mesh.Center.Y);var normal=new Vector3(n.X,n.Z,n.Y);verts.Add(new(pos,normal,new(uv.X,-uv.Y),vi,bone));idxs.Add(checked((ushort)(verts.Count-1)));}var nidx=idxs.Count; (idxs[nidx-3],idxs[nidx-1])=(idxs[nidx-1],idxs[nidx-3]);}var mat=group.MaterialIndex<mats.Count?mats[group.MaterialIndex]:null;var tex=mat?.Frames.FirstOrDefault()?.FileName;var rm=mat is null?null:ToRenderMaterial(mat);primitives.Add(new(mat?.Name??$"material-{group.MaterialIndex}",verts,idxs,tex,false,rm));}}
  var parents=Enumerable.Repeat(-1,skeleton.Bones.Count).ToArray();foreach(var b in skeleton.Bones)foreach(var child in b.Children)parents[child]=b.Index;
  var bones=new List<RenderBone>(skeleton.Bones.Count);foreach(var b in skeleton.Bones){var pose=Pose(doc,source,b.TrackReferenceIndex);bones.Add(new(b.Name,parents[b.Index],pose.Translation,pose.Rotation,pose.Scale));}
  return new(name,primitives,false,new(bones));
 }
 static int BoneFor(SageMesh m,int vertex){foreach(var p in m.MobPieces)if(vertex>=p.Start&&vertex<p.Start+p.Count)return p.BoneIndex;return 0;}
 static SageBoneFrame Pose(WldDocument doc,ReadOnlySpan<byte> source,int trackIndex){if(trackIndex<0||trackIndex>=doc.Fragments.Count)return new(1,Vector3.Zero,Quaternion.Identity);var tr=WldAnimationReader.ReadTrackReference(doc.Fragments[trackIndex],source);if(tr.DefinitionIndex<0||tr.DefinitionIndex>=doc.Fragments.Count)return new(1,Vector3.Zero,Quaternion.Identity);var td=WldAnimationReader.ReadTrackDefinition(doc.Fragments[tr.DefinitionIndex],source);var f=td.Frames.FirstOrDefault()??new(1,Vector3.Zero,Quaternion.Identity);var q=new Quaternion(-f.Rotation.X*MathF.PI/180f,f.Rotation.Z*MathF.PI/180f,f.Rotation.Y*MathF.PI/180f,f.Rotation.W*MathF.PI/180f);if(q.LengthSquared()>0)q=Quaternion.Normalize(q);var t=new Vector3(-f.Translation.X,f.Translation.Z,-f.Translation.Y);return new(f.Scale==0?1:f.Scale,t,q);}
 static RenderMaterial ToRenderMaterial(SageSceneMaterial m){var tex=m.Frames.FirstOrDefault()?.FileName;var alpha=m.Shader switch{SageShaderType.Transparent25=>.25f,SageShaderType.Transparent50 or SageShaderType.TransparentSkydome=>.5f,SageShaderType.Transparent75 or SageShaderType.TransparentAdditive or SageShaderType.TransparentAdditiveUnlit=>.75f,_=>1f};return new(m.Name,tex,m.Shader.ToString(),alpha,m.Shader==SageShaderType.TransparentMasked,m.Shader is SageShaderType.TransparentAdditive or SageShaderType.TransparentAdditiveUnlit or SageShaderType.TransparentAdditiveUnlitSkydome,m.Shader is SageShaderType.TransparentAdditiveUnlit or SageShaderType.TransparentAdditiveUnlitSkydome,m.Frames.Select(x=>x.FileName).ToArray(),m.AnimationDelayMs);}
}