using System.Numerics;using DDVWF.Core.Zone;
namespace DDVWF.Sage.Wld;
public static class SageSkinnedSceneBuilder
{
 public static RenderMesh? Build(WldDocument doc,ReadOnlySpan<byte> source,SageSkeleton skeleton,string name)
 {
  var meshTargets=new List<(int MeshIndex,int BoneIndex)>();
  foreach(var bone in skeleton.Bones){if(bone.MeshReferenceIndex<0||bone.MeshReferenceIndex>=doc.Fragments.Count)continue;var rf=doc.Fragments[bone.MeshReferenceIndex];if(rf.KnownType!=WldFragmentType.MeshReference)continue;var mi=WldMaterialReader.ReadReference(rf,source);if(mi>=0&&mi<doc.Fragments.Count&&doc.Fragments[mi].KnownType is WldFragmentType.Mesh or WldFragmentType.LegacyMesh){meshTargets.Add((mi,bone.Index));}}
  if(meshTargets.Count==0)return null;
  var primitives=new List<RenderPrimitive>();
  foreach(var (mi,targetBone) in meshTargets){var mesh=WldMeshReader.Read(doc,doc.Fragments[mi],source);if(mesh.MaterialListIndex<0||mesh.MaterialListIndex>=doc.Fragments.Count)continue;var list=WldMaterialReader.ReadMaterialList(doc.Fragments[mesh.MaterialListIndex],source);var polygon=0;foreach(var group in mesh.MaterialGroups){var verts=new List<RenderVertex>();var idxs=new List<ushort>();for(var p=0;p<group.PolygonCount;p++){var poly=mesh.Polygons[polygon++];foreach(var vi in new[]{(int)poly.A,(int)poly.B,(int)poly.C}){var bone=mesh.MobPieces.Count>0?BoneFor(mesh,vi):targetBone;var v=mesh.Vertices[vi];var n=mesh.Normals[vi];var uv=mesh.Uvs[vi];var pos=new Vector3(-(v.X+mesh.Center.X),v.Z+mesh.Center.Z,v.Y+mesh.Center.Y);var normal=new Vector3(n.X,n.Z,n.Y);verts.Add(new(pos,normal,new(uv.X,-uv.Y),vi,bone));idxs.Add(checked((ushort)(verts.Count-1)));}var nidx=idxs.Count; (idxs[nidx-3],idxs[nidx-1])=(idxs[nidx-1],idxs[nidx-3]);}SageSceneMaterial? mat=null;if(group.MaterialIndex<list.MaterialIndices.Count)mat=ResolveMaterial(doc,source,list.MaterialIndices[group.MaterialIndex]);var tex=mat?.Frames.FirstOrDefault()?.FileName;var rm=mat is null?null:ToRenderMaterial(mat);primitives.Add(new(mat?.Name??$"material-{group.MaterialIndex}",verts,idxs,tex,false,rm));}}
  var parents=Enumerable.Repeat(-1,skeleton.Bones.Count).ToArray();foreach(var b in skeleton.Bones)foreach(var child in b.Children)parents[child]=b.Index;
  var bones=new List<RenderBone>(skeleton.Bones.Count);foreach(var b in skeleton.Bones){var pose=Pose(doc,source,b.TrackReferenceIndex);bones.Add(new(b.Name,parents[b.Index],pose.Translation,pose.Rotation,pose.Scale));}
  var animations=BuildAnimations(doc,source,skeleton);return new(name,primitives,false,new(bones),animations);
 }
 static IReadOnlyList<RenderAnimation> BuildAnimations(WldDocument doc,ReadOnlySpan<byte> source,SageSkeleton skeleton)
 {
  var poseRefs=skeleton.Bones.Select(b=>b.TrackReferenceIndex).ToHashSet();var groups=new Dictionary<string,Dictionary<string,(SageTrackReference Ref,SageTrackDefinition Def)>>(StringComparer.OrdinalIgnoreCase);
  for(var fi=0;fi<doc.Fragments.Count;fi++){var f=doc.Fragments[fi];if(f.KnownType!=WldFragmentType.TrackReference||poseRefs.Contains(fi))continue;var clean=f.Name.Replace("_TRACK","",StringComparison.OrdinalIgnoreCase).Trim().ToLowerInvariant();if(clean.Length<=3)continue;string anim,model,piece;var global=System.Text.RegularExpressions.Regex.IsMatch(doc.Name,@"global\w{3}_chr",System.Text.RegularExpressions.RegexOptions.IgnoreCase);var am=System.Text.RegularExpressions.Regex.Match(clean,@"[a-z]\d+",System.Text.RegularExpressions.RegexOptions.IgnoreCase);if(global&&am.Success&&(f.Name.EndsWith("_TRACK",StringComparison.OrdinalIgnoreCase)||System.Text.RegularExpressions.Regex.IsMatch(clean,@"_\w+$"))){anim=am.Value.ToLowerInvariant();model=f.Name.EndsWith("_TRACK",StringComparison.OrdinalIgnoreCase)&&clean.Length>=7?clean.Substring(4,3):clean.Length>=3?clean[^3..]:"";piece=f.Name.Length>7?f.Name[7..].Replace("_TRACK","",StringComparison.OrdinalIgnoreCase).ToLowerInvariant():"root";if(piece=="a"||piece.Length==0)piece="root";}else{anim=clean[..3];var rest=clean[3..];if(rest.Length<3)continue;model=rest[..3];piece=rest[3..];if(piece.Length==0)piece="root";}if(!string.Equals(model,skeleton.ModelBase,StringComparison.OrdinalIgnoreCase))continue;var tr=WldAnimationReader.ReadTrackReference(f,source);if(tr.DefinitionIndex<0||tr.DefinitionIndex>=doc.Fragments.Count||doc.Fragments[tr.DefinitionIndex].KnownType!=WldFragmentType.TrackDefinition)continue;var def=WldAnimationReader.ReadTrackDefinition(doc.Fragments[tr.DefinitionIndex],source);piece=CleanBone(piece,skeleton.ModelBase,false);if(!groups.TryGetValue(anim,out var tracks))groups[anim]=tracks=new(StringComparer.OrdinalIgnoreCase);tracks.TryAdd(piece,(tr,def));}
  var output=new List<RenderAnimation>();foreach(var (anim,tracks) in groups){var rt=new List<RenderBoneAnimation>();foreach(var b in skeleton.Bones){var bone=CleanBone(b.Name,skeleton.ModelBase,false);IReadOnlyList<SageBoneFrame> frames;var frameMs=PoseFrameMs(doc,source,b.TrackReferenceIndex);if(tracks.TryGetValue(bone,out var t))frames=t.Def.Frames;else frames=new[]{PoseRaw(doc,source,b.TrackReferenceIndex)};var rf=new List<RenderBoneAnimationFrame>(frames.Count);for(var i=0;i<frames.Count;i++){var x=frames[i];var q=new Quaternion(-x.Rotation.X,x.Rotation.Z,x.Rotation.Y,x.Rotation.W);if(q.LengthSquared()>0)q=Quaternion.Normalize(q);var trn=new Vector3(-x.Translation.X,x.Translation.Z,-x.Translation.Y);var sc=x.Scale==0?1:x.Scale;rf.Add(new(i*Math.Max(0,frameMs)/1000f,trn,q,new(sc,sc,sc)));}rt.Add(new(b.Name,rf));}if(rt.Any(x=>x.Frames.Count>1))output.Add(new(anim,false,rt));}return output;
 }
 static string CleanBone(string name,string modelBase,bool strip){var n=name.Replace("_DAG","",StringComparison.OrdinalIgnoreCase).ToLowerInvariant();if(strip&&n.StartsWith(modelBase,StringComparison.OrdinalIgnoreCase))n=n[modelBase.Length..];return n.Length==0?"root":n;}
 static int PoseFrameMs(WldDocument doc,ReadOnlySpan<byte> source,int idx){if(idx<0||idx>=doc.Fragments.Count)return 0;return WldAnimationReader.ReadTrackReference(doc.Fragments[idx],source).FrameMs;}
 static SageBoneFrame PoseRaw(WldDocument doc,ReadOnlySpan<byte> source,int idx){if(idx<0||idx>=doc.Fragments.Count)return new(1,Vector3.Zero,Quaternion.Identity);var tr=WldAnimationReader.ReadTrackReference(doc.Fragments[idx],source);if(tr.DefinitionIndex<0||tr.DefinitionIndex>=doc.Fragments.Count)return new(1,Vector3.Zero,Quaternion.Identity);return WldAnimationReader.ReadTrackDefinition(doc.Fragments[tr.DefinitionIndex],source).Frames.FirstOrDefault()??new(1,Vector3.Zero,Quaternion.Identity);}
 static int BoneFor(SageMesh m,int vertex){foreach(var p in m.MobPieces)if(vertex>=p.Start&&vertex<p.Start+p.Count)return p.BoneIndex;return 0;}
 static SageBoneFrame Pose(WldDocument doc,ReadOnlySpan<byte> source,int trackIndex){if(trackIndex<0||trackIndex>=doc.Fragments.Count)return new(1,Vector3.Zero,Quaternion.Identity);var tr=WldAnimationReader.ReadTrackReference(doc.Fragments[trackIndex],source);if(tr.DefinitionIndex<0||tr.DefinitionIndex>=doc.Fragments.Count)return new(1,Vector3.Zero,Quaternion.Identity);var td=WldAnimationReader.ReadTrackDefinition(doc.Fragments[tr.DefinitionIndex],source);var f=td.Frames.FirstOrDefault()??new(1,Vector3.Zero,Quaternion.Identity);var q=new Quaternion(-f.Rotation.X,f.Rotation.Z,f.Rotation.Y,f.Rotation.W);if(q.LengthSquared()>0)q=Quaternion.Normalize(q);var t=new Vector3(-f.Translation.X,f.Translation.Z,-f.Translation.Y);return new(f.Scale==0?1:f.Scale,t,q);}
 static SageSceneMaterial? ResolveMaterial(WldDocument doc,ReadOnlySpan<byte> source,int index){if(index<0||index>=doc.Fragments.Count||doc.Fragments[index].KnownType!=WldFragmentType.Material)return null;var f=doc.Fragments[index];var m=WldMaterialReader.ReadMaterial(f,source);var frames=new List<SageTexture>();var delay=0;if(m.BitmapInfoReferenceIndex>=0&&m.BitmapInfoReferenceIndex<doc.Fragments.Count){var rf=doc.Fragments[m.BitmapInfoReferenceIndex];var ii=rf.KnownType==WldFragmentType.FragmentReference?WldMaterialReader.ReadReference(rf,source):m.BitmapInfoReferenceIndex;if(ii>=0&&ii<doc.Fragments.Count&&doc.Fragments[ii].KnownType==WldFragmentType.BitmapInfo){var info=WldMaterialReader.ReadBitmapInfo(doc.Fragments[ii],source);delay=info.AnimationDelayMs;foreach(var bi in info.BitmapNameIndices)if(bi>=0&&bi<doc.Fragments.Count&&doc.Fragments[bi].KnownType==WldFragmentType.BitmapName)frames.Add(new(WldMaterialReader.ReadBitmapName(doc.Fragments[bi],source).FileName));}}return new(f.Name,m.Shader,m.Brightness,m.ScaledAmbient,frames,delay);}
 static RenderMaterial ToRenderMaterial(SageSceneMaterial m){var tex=m.Frames.FirstOrDefault()?.FileName;var blend=m.Shader is SageShaderType.Transparent25 or SageShaderType.Transparent50 or SageShaderType.Transparent75 or SageShaderType.TransparentAdditive or SageShaderType.TransparentAdditiveUnlit or SageShaderType.TransparentSkydome or SageShaderType.TransparentAdditiveUnlitSkydome or SageShaderType.Boundary;var alpha=m.Shader==SageShaderType.Boundary?0f:1f;return new(m.Name,tex,m.Shader.ToString(),alpha,m.Shader==SageShaderType.TransparentMasked,false,false,m.Frames.Select(x=>x.FileName).ToArray(),m.AnimationDelayMs,AlphaBlend:blend);}
}