using System.Buffers.Binary;using System.Numerics;
namespace DDVWF.Sage.Wld;
public sealed record SageBspNode(Vector3 Normal,float SplitDistance,int RegionId,int Left,int Right,Vector3 Min,Vector3 Max);
public sealed record SageBspRegion(int Index,bool ContainsPolygons,int MeshReference);
public sealed record SageRegionType(IReadOnlyList<int> RegionIndices,string Tag);
public static class WldBspReader
{
 public static IReadOnlyList<SageBspNode> ReadTree(WldFragment f,ReadOnlySpan<byte>s){var r=new R(s,f.PayloadOffset);var count=checked((int)r.U());var a=new List<SageBspNode>(count);for(var i=0;i<count;i++)a.Add(new(new(r.F(),r.F(),r.F()),r.F(),r.I(),r.I()-1,r.I()-1,Vector3.Zero,Vector3.Zero));return a;}
 public static SageBspRegion ReadRegion(int index,WldFragment f,ReadOnlySpan<byte>s){var r=new R(s,f.PayloadOffset);var flags=r.I();_=r.I();var d1=r.I();var d2=r.I();_=r.I();var d3=r.I();var d4=r.I();_=r.I();var d5=r.I();_=r.I();r.Skip(checked(12*(d1+d2)));for(var i=0;i<d3;i++){_=r.I();var n=r.I();r.Skip(checked(n*4));}if(d4!=0)throw new InvalidDataException("Sage BSP data4 branch is source-unimplemented and cannot be guessed.");r.Skip(checked(d5*28));var pvs=r.I16();if(pvs<0)throw new InvalidDataException("Negative BSP PVS size.");r.Skip(pvs);_=r.U();r.Skip(16);var mesh=flags==0x181?r.I():-1;return new(index,flags==0x181,mesh);}
 public static SageRegionType ReadType(WldDocument doc,WldFragment f,ReadOnlySpan<byte>s){var r=new R(s,f.PayloadOffset);_=r.I();var count=r.I();if(count<0)throw new InvalidDataException("Negative region count.");var ids=new List<int>(count);for(var i=0;i<count;i++)ids.Add(r.I());var n=r.I();if(n<0)throw new InvalidDataException("Negative region tag size.");var bytes=r.Bytes(n);for(var i=0;i<bytes.Length;i++)bytes[i]^=new byte[]{0x95,0x3A,0xC5,0x2A,0x95,0x7A,0x95,0x6A}[i&7];var tag=System.Text.Encoding.Latin1.GetString(bytes).TrimEnd('\0').ToLowerInvariant();return new(ids,string.IsNullOrWhiteSpace(tag)?f.Name.ToLowerInvariant():tag);}
 sealed class R{readonly byte[]b;int p;public R(ReadOnlySpan<byte>s,int o){b=s.ToArray();p=o;}void N(int n){if(n<0||p+n>b.Length)throw new InvalidDataException("BSP fragment truncated.");}public uint U(){N(4);var v=BinaryPrimitives.ReadUInt32LittleEndian(b.AsSpan(p,4));p+=4;return v;}public int I()=>unchecked((int)U());public short I16(){N(2);var v=BinaryPrimitives.ReadInt16LittleEndian(b.AsSpan(p,2));p+=2;return v;}public float F()=>BitConverter.Int32BitsToSingle(I());public void Skip(int n){N(n);p+=n;}public byte[] Bytes(int n){N(n);var x=b.AsSpan(p,n).ToArray();p+=n;return x;}}
}