<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DragonDenVisualWorldForge</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DDVWF.Core/DDVWF.Core.csproj" />
    <ProjectReference Include="../DDVWF.Server/DDVWF.Server.csproj" />
  </ItemGroup>
</Project>
