using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using DDVWF.Core.Workspace;

namespace DDVWF.App;

public sealed class ThemeEditorWindow:Window
{
    static readonly string[] Keys=ThemeSettings.DefaultPalette().Keys.ToArray();
    readonly Dictionary<string,string> colors;readonly Dictionary<string,string> original;readonly Dictionary<string,Dictionary<string,string>> slots=new();readonly string slotFile=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"DragonDenWorldForge","theme-slots.json");readonly Action<ThemeSettings> preview;readonly UniformGrid grid=new(){Columns=2};readonly TextBlock notice=new(){Margin=new Thickness(8,0,0,0),VerticalAlignment=VerticalAlignment.Center};public ThemeSettings Settings{get;private set;}
    public ThemeEditorWindow(ThemeSettings value,Action<ThemeSettings> live)
    {
        Settings=value;preview=live;colors=ThemeSettings.DefaultPalette();foreach(var p in value.Palette)colors[p.Key]=p.Value;original=new(colors,StringComparer.OrdinalIgnoreCase);try{if(File.Exists(slotFile)){var saved=System.Text.Json.JsonSerializer.Deserialize<Dictionary<string,Dictionary<string,string>>>(File.ReadAllText(slotFile));if(saved is not null)foreach(var p in saved)slots[p.Key]=new(p.Value,StringComparer.OrdinalIgnoreCase);}}catch(Exception ex){notice.Text="Palette slots: "+ex.Message;}
        Title="THEME EDITOR";Width=940;Height=680;MinWidth=860;MinHeight=360;ResizeMode=ResizeMode.CanResize;FontFamily=new FontFamily("Verdana");FontSize=12;WindowStartupLocation=WindowStartupLocation.CenterOwner;Background=B("#08070C");Foreground=B("#D7FF00");
        var dock=new DockPanel();var actions=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(5)};DockPanel.SetDock(actions,Dock.Bottom);
        for(int n=1;n<=3;n++){var id=n.ToString();var slot=new Button{Content="Custom "+n,Tag=id,Margin=new Thickness(1),Padding=new Thickness(5,1,5,1)};slot.Click+=(_,_)=>{if(!slots.TryGetValue(id,out var saved))return;foreach(var p in saved)if(colors.ContainsKey(p.Key))colors[p.Key]=p.Value;Rebuild();preview(Build());};actions.Children.Add(slot);var slotSave=new Button{Content="Save",Tag=id,Margin=new Thickness(1),Padding=new Thickness(5,1,5,1)};slotSave.Click+=(_,_)=>{slots[id]=new(colors,StringComparer.OrdinalIgnoreCase);try{Directory.CreateDirectory(Path.GetDirectoryName(slotFile)!);File.WriteAllText(slotFile,System.Text.Json.JsonSerializer.Serialize(slots));notice.Text="Custom "+id+" saved";}catch(Exception ex){notice.Text="Palette slot save failed: "+ex.Message;}};actions.Children.Add(slotSave);}
        var save=new Button{Content="Save Current Palette",Margin=new Thickness(6,1,1,1)};save.Click+=(_,_)=>{Settings=Build();DialogResult=true;Close();};actions.Children.Add(save);
        var revert=new Button{Content="Revert Unsaved",Margin=new Thickness(1)};revert.Click+=(_,_)=>{colors.Clear();foreach(var p in original)colors[p.Key]=p.Value;Rebuild();preview(Build());};actions.Children.Add(revert);actions.Children.Add(notice);dock.Children.Add(actions);
        var scroll=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Auto};scroll.Content=grid;dock.Children.Add(scroll);Content=DdvwfChrome.Wrap(this,"THEME EDITOR",dock,value);DdvwfChrome.AttachPersistentGeometry(this,"theme");Rebuild();
        PreviewKeyDown+=(_,e)=>{if(e.Key==Key.Escape){DialogResult=false;Close();}};
    }
    static SolidColorBrush B(string s)=>new((Color)ColorConverter.ConvertFromString(s));
    ThemeSettings Build()=>Settings with{Palette=new Dictionary<string,string>(colors,StringComparer.OrdinalIgnoreCase),Accent=colors["AccentBrush"],Separator=colors["DividerBrush"],Compass=colors["CompassAccentBrush"],ListText=colors["ListTextBrush"],WindowBackground=colors["ViewportBrush"],PanelBackground=colors["PanelBrush"],ControlBackground=colors["Panel2Brush"],MutedText=colors["MutedTextBrush"]};
    static string Label(string k)=>k switch{"ModelLibraryBackgroundBrush"=>"Library BG","InputBrush"=>"Text Entry BG","ScrollTrackBrush"=>"Scrollbar Track","ScrollThumbBrush"=>"Scrollbar Thumb","CompassBackgroundBrush"=>"Compass BG","CompassDegreeTextBrush"=>"Compass Degrees","CompassTickBrush"=>"Compass Ticks","CompassCardinalBrush"=>"Compass NSEW",_=>k.Replace("Brush","")};
    void Rebuild(){grid.Children.Clear();foreach(var k in Keys){var row=new Grid{Height=24,Margin=new Thickness(4,1,4,1)};row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(270)});row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(42)});row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(108)});row.Children.Add(new TextBlock{Text=Label(k),VerticalAlignment=VerticalAlignment.Center});var sw=new Button{Tag=k,Background=B(colors[k]),BorderBrush=B(colors["ControlBorderBrush"]),BorderThickness=new Thickness(1),Margin=new Thickness(2)};sw.Click+=Swatch;Grid.SetColumn(sw,1);row.Children.Add(sw);var hex=new TextBlock{Text=Argb(colors[k]),VerticalAlignment=VerticalAlignment.Center};Grid.SetColumn(hex,2);row.Children.Add(hex);grid.Children.Add(row);}}
    static string Argb(string s){var c=(Color)ColorConverter.ConvertFromString(s);return $"#{c.A:X2}{c.R:X2}{c.G:X2}{c.B:X2}";}
    void Swatch(object sender,RoutedEventArgs e){var button=(Button)sender;var key=(string)button.Tag;var before=colors[key];var initial=(Color)ColorConverter.ConvertFromString(before);VwfColorPicker? p=null;p=new VwfColorPicker(initial,c=>{colors[key]=$"#{c.A:X2}{c.R:X2}{c.G:X2}{c.B:X2}";button.Background=new SolidColorBrush(c);preview(Build());},Build());p.Owner=this;p.RefreshChrome();if(p.ShowDialog()==true){colors[key]=$"#{p.SelectedColor.A:X2}{p.SelectedColor.R:X2}{p.SelectedColor.G:X2}{p.SelectedColor.B:X2}";Rebuild();preview(Build());}else{colors[key]=before;Rebuild();preview(Build());}}
}

public sealed class ShortcutEditorWindow:Window
{
    readonly Dictionary<string,TextBox> boxes=new(StringComparer.OrdinalIgnoreCase);readonly Dictionary<string,string> defaults=WorkspaceSettings.ShortcutDefaults();readonly Action<IReadOnlyDictionary<string,string>> changed;string? prior;public Dictionary<string,string> Shortcuts{get;private set;}
    static readonly Dictionary<string,string> Desc=new(StringComparer.OrdinalIgnoreCase){{"Select","Select / release"},{"Move","Move gizmo"},{"Rotate","Rotate gizmo"},{"Scale","Scale gizmo"},{"Snap","Snap action"},{"Focus","Focus selection"},{"ResetSelection","ResetSelection action"},{"Undo","Undo action"},{"Redo","Redo action"},{"ResetAll","ResetAll action"},{"Release","Release action"},{"CameraUp","Camera vertical +"},{"CameraDown","Camera vertical -"}};
    public ShortcutEditorWindow(IReadOnlyDictionary<string,string> value,ThemeSettings theme,Action<IReadOnlyDictionary<string,string>> changed)
    {
        this.changed=changed;Shortcuts=new(defaults,StringComparer.OrdinalIgnoreCase);foreach(var p in value)if(defaults.ContainsKey(p.Key))Shortcuts[p.Key]=p.Value;Title="SHORTCUTS";Width=430;Height=360;MinWidth=380;MinHeight=220;ResizeMode=ResizeMode.CanResize;FontFamily=new FontFamily("Verdana");FontSize=12;WindowStartupLocation=WindowStartupLocation.CenterOwner;Background=B("#08070C");Foreground=B("#D7FF00");
        var dock=new DockPanel();var actions=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(5)};DockPanel.SetDock(actions,Dock.Bottom);var reset=new Button{Content="Restore Defaults",Margin=new Thickness(1)};reset.Click+=(_,_)=>{Shortcuts=new(defaults,StringComparer.OrdinalIgnoreCase);foreach(var p in defaults)boxes[p.Key].Text=p.Value;changed(Shortcuts);};actions.Children.Add(reset);dock.Children.Add(actions);
        var panel=new StackPanel{Margin=new Thickness(5)};var scroll=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Auto,Content=panel};dock.Children.Add(scroll);Content=DdvwfChrome.Wrap(this,"SHORTCUTS",dock,theme);DdvwfChrome.AttachPersistentGeometry(this,"shortcuts");
        foreach(var p in defaults){var row=new Grid{Height=24};row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(105)});row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(92)});row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(130)});row.Children.Add(new TextBlock{Text=p.Key,VerticalAlignment=VerticalAlignment.Center});var box=new TextBox{Text=Shortcuts[p.Key],Tag=p.Key,IsReadOnly=true,Focusable=true,Margin=new Thickness(2),Padding=new Thickness(3,0,3,0)};box.GotKeyboardFocus+=CaptureFocus;box.PreviewKeyDown+=Capture;boxes[p.Key]=box;Grid.SetColumn(box,1);row.Children.Add(box);var desc=new TextBlock{Text=Desc.TryGetValue(p.Key,out var d)?d:p.Key+" action",VerticalAlignment=VerticalAlignment.Center,TextTrimming=TextTrimming.CharacterEllipsis};Grid.SetColumn(desc,2);row.Children.Add(desc);panel.Children.Add(row);}
        PreviewKeyDown+=(_,e)=>{if(e.Key==Key.Escape&&Keyboard.FocusedElement is not TextBox){DialogResult=false;Close();}};
    }
    static SolidColorBrush B(string s)=>new((Color)ColorConverter.ConvertFromString(s));
    void CaptureFocus(object sender,RoutedEventArgs e){var b=(TextBox)sender;prior=b.Text;b.Text="Press shortcut...";b.SelectAll();}
    void Capture(object sender,KeyEventArgs e){var box=(TextBox)sender;e.Handled=true;if(e.Key==Key.Escape){box.Text=prior??defaults[(string)box.Tag];Keyboard.ClearFocus();return;}var key=e.Key==Key.System?e.SystemKey:e.Key;if(key is Key.LeftCtrl or Key.RightCtrl or Key.LeftShift or Key.RightShift or Key.LeftAlt or Key.RightAlt or Key.LWin or Key.RWin)return;var parts=new List<string>();var m=Keyboard.Modifiers;if(m.HasFlag(ModifierKeys.Control))parts.Add("Ctrl");if(m.HasFlag(ModifierKeys.Shift))parts.Add("Shift");if(m.HasFlag(ModifierKeys.Alt))parts.Add("Alt");if(m.HasFlag(ModifierKeys.Windows))parts.Add("Win");parts.Add(key.ToString());var chord=string.Join("+",parts);if(boxes.Values.Any(x=>!ReferenceEquals(x,box)&&string.Equals(x.Text,chord,StringComparison.OrdinalIgnoreCase))){box.Text=prior??defaults[(string)box.Tag];return;}box.Text=chord;Shortcuts[(string)box.Tag]=chord;changed(Shortcuts);Keyboard.ClearFocus();}
}