using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;using DDVWF.Core.Workspace;
namespace DDVWF.App;
public sealed class ThemeEditorWindow:Window
{
 readonly TextBox accent=new(),separator=new(),compass=new(),list=new(),windowBackground=new(),panelBackground=new(),controlBackground=new(),mutedText=new();readonly Action<ThemeSettings> preview;public ThemeSettings Settings{get;private set;}
 public ThemeEditorWindow(ThemeSettings value,Action<ThemeSettings> live){Settings=value;preview=live;Title="Theme Editor";Width=430;Height=390;MinWidth=380;MinHeight=320;FontFamily=new FontFamily("Verdana");FontSize=12;WindowStartupLocation=WindowStartupLocation.CenterOwner;var scroll=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto};var panel=new StackPanel{Margin=new Thickness(14)};scroll.Content=panel;Content=scroll;Add("Accent",accent,value.Accent);Add("Separator",separator,value.Separator);Add("Compass",compass,value.Compass);Add("List text",list,value.ListText);Add("Window background",windowBackground,value.WindowBackground);Add("Panel background",panelBackground,value.PanelBackground);Add("Control background",controlBackground,value.ControlBackground);Add("Muted text",mutedText,value.MutedText);var save=new Button{Content="Save Color",Margin=new Thickness(0,18,0,0),MinHeight=30};save.Click+=(_,_)=>{if(!TryRead(out var s))return;Settings=s;DialogResult=true;Close();};panel.Children.Add(save);PreviewKeyDown+=(_,e)=>{if(e.Key==Key.Escape){DialogResult=false;Close();}};void Add(string label,TextBox box,string value){panel.Children.Add(new TextBlock{Text=label,Margin=new Thickness(0,8,0,2)});box.Text=value;box.TextChanged+=(_,_)=>{if(TryRead(out var s))preview(s);};panel.Children.Add(box);}}
 bool TryRead(out ThemeSettings s){s=new(accent.Text,separator.Text,compass.Text,list.Text,windowBackground.Text,panelBackground.Text,controlBackground.Text,mutedText.Text);try{_ = (Color)ColorConverter.ConvertFromString(s.Accent);_=(Color)ColorConverter.ConvertFromString(s.Separator);_=(Color)ColorConverter.ConvertFromString(s.Compass);_=(Color)ColorConverter.ConvertFromString(s.ListText);_=(Color)ColorConverter.ConvertFromString(s.WindowBackground);_=(Color)ColorConverter.ConvertFromString(s.PanelBackground);_=(Color)ColorConverter.ConvertFromString(s.ControlBackground);_=(Color)ColorConverter.ConvertFromString(s.MutedText);return true;}catch{return false;}}
}
public sealed class ShortcutEditorWindow:Window
{
 readonly Dictionary<string,TextBox> boxes=new();public Dictionary<string,string> Shortcuts{get;private set;}
 public ShortcutEditorWindow(IReadOnlyDictionary<string,string> value){Shortcuts=new(value,StringComparer.OrdinalIgnoreCase);Title="Shortcuts";Width=460;Height=520;MinWidth=400;MinHeight=350;FontFamily=new FontFamily("Verdana");FontSize=12;WindowStartupLocation=WindowStartupLocation.CenterOwner;var scroll=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto};var panel=new StackPanel{Margin=new Thickness(14)};scroll.Content=panel;Content=scroll;foreach(var name in new[]{"Select","Move","Rotate","Scale","Focus","Delete","Duplicate","Stamp"}){panel.Children.Add(new TextBlock{Text=name,Margin=new Thickness(0,7,0,2)});var b=new TextBox{Text=value.TryGetValue(name,out var v)?v:""};boxes[name]=b;panel.Children.Add(b);}var save=new Button{Content="Save Shortcuts",Margin=new Thickness(0,18,0,0),MinHeight=30};save.Click+=(_,_)=>{Shortcuts=boxes.ToDictionary(x=>x.Key,x=>x.Value.Text.Trim(),StringComparer.OrdinalIgnoreCase);DialogResult=true;Close();};panel.Children.Add(save);PreviewKeyDown+=(_,e)=>{if(e.Key==Key.Escape){DialogResult=false;Close();}};}
}