using System.IO;
using System.Windows;
using DDVWF.Core.Commands;
using DDVWF.Core.Workspace;
using DDVWF.Core.Zone;
using DDVWF.Sage;
using DDVWF.Server;
using DDVWF.Renderer.Babylon;

namespace DDVWF.App;
public partial class MainWindow:Window
{
 readonly CommandHistory _history=new();readonly JsonWorkspaceStore _workspace;WorkspaceSettings _settings=new();ZoneSession? _session; SageClientZoneProvider? _client;Guid? _selectedId;string? _modelViewerAsset;CompassWindow? _compass;
 public MainWindow(){InitializeComponent();var buildPath=Environment.ProcessPath??System.Reflection.Assembly.GetExecutingAssembly().Location;var buildTime=File.GetLastWriteTime(buildPath);Title=$"Dragon's Den Visual WorldForge | DEFAULT Foundation5R7R40 | TEST CompleteZoneIR | Build {buildTime:yyyy-MM-dd HH:mm}";DdvwfTitleText.Text=Title;Viewport.CoreWebView2InitializationCompleted+=(_,e)=>{if(!e.IsSuccess)StatusText.Text=$"Renderer failed: {e.InitializationException?.Message}";};var root=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"DragonsDen","DDVWF");_workspace=new(Path.Combine(root,"workspace.json"));Loaded+=async(_,_)=>await RestoreAsync();Closing+=async(_,_)=>{if(_compass is not null)_settings.Windows["Compass"]=new DDVWF.Core.Workspace.WindowState(_compass.Left,_compass.Top,_compass.Width,_compass.Height,_compass.WindowState==System.Windows.WindowState.Minimized);await PersistAsync();};PreviewKeyDown+=ShortcutKeyDown;}
 void TitleBar_MouseLeftButtonDown(object sender,System.Windows.Input.MouseButtonEventArgs e){if(e.ClickCount==2){WindowState=WindowState==System.Windows.WindowState.Maximized?System.Windows.WindowState.Normal:System.Windows.WindowState.Maximized;e.Handled=true;return;}if(e.LeftButton==System.Windows.Input.MouseButtonState.Pressed)DragMove();}
 void Minimize_Click(object sender,RoutedEventArgs e)=>WindowState=System.Windows.WindowState.Minimized;
 void Maximize_Click(object sender,RoutedEventArgs e)=>WindowState=WindowState==System.Windows.WindowState.Maximized?System.Windows.WindowState.Normal:System.Windows.WindowState.Maximized;

 void ShortcutKeyDown(object sender,System.Windows.Input.KeyEventArgs e){foreach(var pair in _settings.Shortcuts){try{if(new System.Windows.Input.KeyGestureConverter().ConvertFromString(pair.Value) is not System.Windows.Input.KeyGesture g||!g.Matches(this,e))continue;e.Handled=true;switch(pair.Key){case "Select":SelectMode_Click(this,new RoutedEventArgs());break;case "Move":MoveMode_Click(this,new RoutedEventArgs());break;case "Rotate":RotateMode_Click(this,new RoutedEventArgs());break;case "Scale":ScaleMode_Click(this,new RoutedEventArgs());break;case "Focus":Focus_Click(this,new RoutedEventArgs());break;case "Delete":Delete_Click(this,new RoutedEventArgs());break;case "Duplicate":Duplicate_Click(this,new RoutedEventArgs());break;case "Stamp":Stamp_Click(this,new RoutedEventArgs());break;case "Undo":Undo_Click(this,new RoutedEventArgs());break;case "Redo":Redo_Click(this,new RoutedEventArgs());break;}return;}catch{}}}
  async Task NavigateRendererAsync(Microsoft.Web.WebView2.Wpf.WebView2 view,Uri source){var tcs=new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);void Done(object? s,Microsoft.Web.WebView2.Core.CoreWebView2NavigationCompletedEventArgs e){view.NavigationCompleted-=Done;if(e.IsSuccess)tcs.TrySetResult(true);else tcs.TrySetException(new InvalidOperationException("Renderer navigation failed: "+e.WebErrorStatus));}view.NavigationCompleted+=Done;view.Source=source;await tcs.Task;}
  async Task RestoreAsync(){await Viewport.EnsureCoreWebView2Async();await ModelViewer.EnsureCoreWebView2Async();var html=Path.Combine(AppContext.BaseDirectory,"Renderer","babylon.html");if(!File.Exists(html)){StatusText.Text="Renderer failed: babylon.html is missing.";return;}var rendererUri=new Uri(html);await Task.WhenAll(NavigateRendererAsync(Viewport,rendererUri),NavigateRendererAsync(ModelViewer,rendererUri));Viewport.WebMessageReceived+=Viewport_WebMessageReceived;ModelViewer.WebMessageReceived+=ModelViewer_WebMessageReceived;_settings=await _workspace.LoadAsync();var migrated=false;var legacyTheme=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"DragonDenWorldForge","theme.json");if(!_settings.LegacyThemeImported&&File.Exists(legacyTheme)){try{var legacy=System.Text.Json.JsonSerializer.Deserialize<Dictionary<string,string>>(await File.ReadAllTextAsync(legacyTheme));if(legacy is not null&&legacy.Count>0){var p=ThemeSettings.DefaultPalette();foreach(var x in legacy)if(p.ContainsKey(x.Key))p[x.Key]=x.Value;_settings=_settings with{Theme=_settings.Theme with{Palette=p,Accent=p["AccentBrush"],Separator=p["DividerBrush"],Compass=p["CompassAccentBrush"],ListText=p["ListTextBrush"],WindowBackground=p["ViewportBrush"],PanelBackground=p["PanelBrush"],ControlBackground=p["Panel2Brush"],MutedText=p["MutedTextBrush"]}};_settings=_settings with{LegacyThemeImported=true};migrated=true;}}catch(Exception ex){StatusText.Text=$"Legacy theme import warning: {ex.Message}";}}if(string.IsNullOrWhiteSpace(_settings.EqRoot)){_settings=_settings with{EqRoot=@"S:\EQ"};migrated=true;}if(string.Equals(_settings.Server.Database,"peq",StringComparison.OrdinalIgnoreCase)){_settings=_settings with{Server=_settings.Server with{Database="eqemu_peq"}};migrated=true;}if(migrated)await PersistAsync();ApplyTheme(_settings.Theme);RestoreBottomPaneWidths();StatusText.Text=string.IsNullOrWhiteSpace(_settings.EqRoot)?"Choose EverQuest directory":_settings.EqRoot;if(!string.IsNullOrWhiteSpace(_settings.EqRoot)&&Directory.Exists(_settings.EqRoot)){DiscoverZones();if(!string.IsNullOrWhiteSpace(_settings.LastZone))await OpenZoneAsync(_settings.LastZone);}}
 void RestoreBottomPaneWidths(){var cols=new[]{("Bottom.Status",BottomStatusColumn),("Bottom.Difference",BottomDifferenceColumn),("Bottom.Diagnostics",BottomDiagnosticsColumn),("Bottom.Native",BottomNativeColumn),("Bottom.Changes",BottomChangesColumn),("Bottom.Console",BottomConsoleColumn),("Bottom.Inspector",BottomInspectorColumn)};foreach(var (key,col) in cols)if(_settings.Dividers.TryGetValue(key,out var saved)&&saved>=col.MinWidth)col.Width=new GridLength(saved,GridUnitType.Pixel);}
 async void BottomSplitter_DragCompleted(object sender,System.Windows.Controls.Primitives.DragCompletedEventArgs e){_settings.Dividers["Bottom.Status"]=BottomStatusColumn.ActualWidth;_settings.Dividers["Bottom.Difference"]=BottomDifferenceColumn.ActualWidth;_settings.Dividers["Bottom.Diagnostics"]=BottomDiagnosticsColumn.ActualWidth;_settings.Dividers["Bottom.Native"]=BottomNativeColumn.ActualWidth;_settings.Dividers["Bottom.Changes"]=BottomChangesColumn.ActualWidth;_settings.Dividers["Bottom.Console"]=BottomConsoleColumn.ActualWidth;_settings.Dividers["Bottom.Inspector"]=BottomInspectorColumn.ActualWidth;await PersistAsync();}
 void DiscoverZones(){AssetTree.Items.Clear();foreach(var p in Directory.EnumerateFiles(_settings.EqRoot!,"*.s3d",SearchOption.TopDirectoryOnly).Where(x=>!Path.GetFileNameWithoutExtension(x).EndsWith("_obj",StringComparison.OrdinalIgnoreCase)&&!Path.GetFileNameWithoutExtension(x).EndsWith("_obj2",StringComparison.OrdinalIgnoreCase)).OrderBy(Path.GetFileName)){var z=Path.GetFileNameWithoutExtension(p);var item=new System.Windows.Controls.TreeViewItem{Header=z,Tag=z};item.MouseDoubleClick+=async(_,_)=>await OpenZoneAsync(z);AssetTree.Items.Add(item);}}
 async Task OpenZoneAsync(string zone){try{StatusText.Text=$"Loading {zone}...";_client=new SageClientZoneProvider();IServerDataProvider server=new NoServerDataProvider();if(_settings.Server.Enabled&&!string.IsNullOrWhiteSpace(_settings.Server.User)&&!string.IsNullOrWhiteSpace(_settings.Server.Password))server=EqEmuMySqlConnection.CreateReadProvider(new(_settings.Server.Host,_settings.Server.Port,_settings.Server.Database,_settings.Server.User,_settings.Server.Password));_session=new(_client,server,new SceneTreeViewport(SceneTree));var loaded=await _session.OpenAsync(_settings.EqRoot!,zone);var worldEntities=loaded.Entities.Where(e=>e.Kind==ZoneEntityKind.WorldGeometry).ToArray();var worldRenderable=worldEntities.Count(e=>e.ClientAsset is not null&&_client.RenderMeshes.ContainsKey(e.ClientAsset));var worldPrimitives=worldEntities.Where(e=>e.ClientAsset is not null&&_client.RenderMeshes.ContainsKey(e.ClientAsset)).Sum(e=>_client.RenderMeshes[e.ClientAsset!].Primitives.Count);var worldTriangles=worldEntities.Where(e=>e.ClientAsset is not null&&_client.RenderMeshes.ContainsKey(e.ClientAsset)).Sum(e=>_client.RenderMeshes[e.ClientAsset!].Primitives.Sum(p=>p.Indices.Count/3));var objectTotal=loaded.Entities.Count(e=>e.Kind is ZoneEntityKind.StaticObject or ZoneEntityKind.AnimatedObject);var objectRenderable=loaded.Entities.Count(e=>(e.Kind is ZoneEntityKind.StaticObject or ZoneEntityKind.AnimatedObject)&&e.ClientAsset is not null&&_client.RenderMeshes.ContainsKey(e.ClientAsset));if(worldRenderable==0)throw new InvalidDataException($"Sage produced no renderable world geometry for {zone}.");var payload=BabylonSceneSerializer.Serialize(loaded,_client.RenderMeshes,_client.TextureFiles);await Viewport.CoreWebView2.ExecuteScriptAsync($"window.ddvwf.loadScene({System.Text.Json.JsonSerializer.Serialize(payload)})");await Viewport.CoreWebView2.ExecuteScriptAsync("window.ddvwf.frameWorld()");_settings=_settings with{LastZone=zone};PopulateAssetViewers(loaded);ZoneText.Text=$"{zone}  |  {loaded.Entities.Count} entities";StatusText.Text=$"Loaded {zone} | world {worldRenderable} meshes, {worldPrimitives} prims, {worldTriangles} tris | objects {objectRenderable}/{objectTotal}";await PersistAsync();}catch(Exception ex){StatusText.Text=$"Load failed: {ex.Message}";}}
 static float JsonFloat(System.Text.Json.JsonElement root,string name,float fallback=0){if(!root.TryGetProperty(name,out var v)||v.ValueKind!=System.Text.Json.JsonValueKind.Number||!v.TryGetSingle(out var n)||float.IsNaN(n)||float.IsInfinity(n))return fallback;return n;}
 void ModelViewer_WebMessageReceived(object? sender,Microsoft.Web.WebView2.Core.CoreWebView2WebMessageReceivedEventArgs e){try{if(string.IsNullOrWhiteSpace(_modelViewerAsset))return;using var d=System.Text.Json.JsonDocument.Parse(e.TryGetWebMessageAsString());var root=d.RootElement;if(root.GetProperty("type").GetString()!="camera")return;_settings.ModelCameras[_modelViewerAsset]=new(JsonFloat(root,"x"),JsonFloat(root,"y"),JsonFloat(root,"z"),JsonFloat(root,"yaw"),JsonFloat(root,"pitch"),JsonFloat(root,"speed",20));}catch(Exception ex){StatusText.Text=$"Model Viewer message failed: {ex.Message}";}}
 void Viewport_WebMessageReceived(object? sender,Microsoft.Web.WebView2.Core.CoreWebView2WebMessageReceivedEventArgs e){try{using var d=System.Text.Json.JsonDocument.Parse(e.TryGetWebMessageAsString());var root=d.RootElement;var type=root.GetProperty("type").GetString();if(type=="camera"){var x=root.GetProperty("x").GetSingle();var y=root.GetProperty("y").GetSingle();var z=root.GetProperty("z").GetSingle();var yaw=root.GetProperty("yaw").GetSingle();var pitch=root.GetProperty("pitch").GetSingle();var speed=root.GetProperty("speed").GetSingle();CoordText.Text=$"EQ X {x:0.00}  Y {y:0.00}  Z {z:0.00}";_settings=_settings with{Camera=new(x,y,z,yaw,pitch,speed)};_compass?.SetHeading(yaw);return;}if(type=="heading"){var yaw=JsonFloat(root,"yaw",_settings.Camera.Yaw);_settings=_settings with{Camera=_settings.Camera with{Yaw=yaw}};_compass?.SetHeading(yaw);return;}if(type=="worldBounds"){return;}if(type=="cameraSpeed"){var speed=root.GetProperty("speed").GetSingle();_settings=_settings with{Camera=_settings.Camera with{Speed=speed}};return;}if(!Guid.TryParse(root.GetProperty("id").GetString(),out var id)||_session?.ActiveZone is not{} zone||!zone.Contains(id))return;if(type=="transform"){var before=zone.Get(id);var pos=new EqPosition(root.GetProperty("x").GetSingle(),root.GetProperty("y").GetSingle(),root.GetProperty("z").GetSingle(),root.GetProperty("heading").GetSingle());var rotation=root.TryGetProperty("rotateX",out var rx)&&root.TryGetProperty("rotateY",out var ry)&&root.TryGetProperty("rotateZ",out var rz)?new EqRotation(rx.GetSingle(),ry.GetSingle(),rz.GetSingle()):zone.Get(id).Rotation;_history.Execute(new TransformCommand(zone,id,pos,root.GetProperty("scale").GetSingle(),rotation));StatusText.Text=$"Transformed {before.Name}";ShowInspector(zone.Get(id));return;}if(type!="select")return;_selectedId=id;ShowInspector(zone.Get(id));}catch(Exception ex){StatusText.Text=$"Viewport message failed: {ex.Message}";}}
 void ShowInspector(ZoneEntity entity){InspectorPanel.Children.Clear();InspectorPanel.Children.Add(new System.Windows.Controls.TextBlock{Text=$"{entity.Kind}: {entity.Name}"});InspectorPanel.Children.Add(new System.Windows.Controls.TextBlock{Text=$"X {entity.Position.X:0.00}  Y {entity.Position.Y:0.00}  Z {entity.Position.Z:0.00}  H {entity.Position.Heading:0.00}  Scale {entity.Scale:0.000}"});if(entity.Rotation is EqRotation rot)InspectorPanel.Children.Add(new System.Windows.Controls.TextBlock{Text=$"Rotation X {rot.X:0.00}  Y {rot.Y:0.00}  Z {rot.Z:0.00}"});if(entity.ServerId is long sid)InspectorPanel.Children.Add(new System.Windows.Controls.TextBlock{Text=$"EQEmu ID {sid}"});if(!string.IsNullOrWhiteSpace(entity.ClientAsset))InspectorPanel.Children.Add(new System.Windows.Controls.TextBlock{Text=$"Native asset: {entity.ClientAsset}",TextWrapping=TextWrapping.Wrap});var detail=entity.Data switch{SpawnEntityData s=>$"Spawn group {s.SpawnGroupId} | Respawn {s.RespawnTime}s | Variance {s.Variance} | Grid {s.PathGrid}",NpcEntityData n=>$"NPC type {n.NpcTypeId} | Group {n.SpawnGroupId} | Chance {n.Chance}% | Race {n.Race} | Gender {n.Gender}",DoorEntityData d=>$"Door ID {d.DoorId} | Open type {d.OpenType}",ZonePointEntityData p=>$"Zone point {p.Number} v{p.Version} -> zone {p.TargetZoneId} instance {p.TargetInstance} | target {p.TargetX:0.00}, {p.TargetY:0.00}, {p.TargetZ:0.00} h {p.TargetHeading:0.00}",_=>null};if(detail is not null)InspectorPanel.Children.Add(new System.Windows.Controls.TextBlock{Text=detail,TextWrapping=TextWrapping.Wrap});StatusText.Text=$"Selected {entity.Name}";_ = RenderModelViewerAsync(entity);}
 void PopulateAssetViewers(CompleteZone zone){ObjectList.Items.Clear();foreach(var e in zone.Entities.Where(x=>x.Kind is ZoneEntityKind.StaticObject or ZoneEntityKind.AnimatedObject).OrderBy(x=>x.Name))ObjectList.Items.Add(new System.Windows.Controls.ListBoxItem{Content=e.Name,Tag=e.Id});TextureList.Items.Clear();if(_client is not null)foreach(var t in _client.TextureFiles.Keys.OrderBy(x=>x))TextureList.Items.Add(t);MaterialList.Items.Clear();if(_client is not null)foreach(var m in _client.RenderMeshes.Values.SelectMany(x=>x.Primitives).Select(x=>x.Material?.Name).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x))MaterialList.Items.Add(m);PopulateActiveZoneAssetTree(zone);}
 void PopulateActiveZoneAssetTree(CompleteZone zone){AssetTree.Items.Clear();var root=new System.Windows.Controls.TreeViewItem{Header=zone.ShortName,IsExpanded=true};foreach(var group in new[]{(ZoneEntityKind.WorldGeometry,"World Geometry"),(ZoneEntityKind.StaticObject,"Objects"),(ZoneEntityKind.AnimatedObject,"Animated Objects"),(ZoneEntityKind.Light,"Lights"),(ZoneEntityKind.Region,"Regions"),(ZoneEntityKind.Door,"Doors"),(ZoneEntityKind.Npc,"NPCs"),(ZoneEntityKind.Spawn,"Spawns"),(ZoneEntityKind.ZonePoint,"Zone Points")}){var branch=new System.Windows.Controls.TreeViewItem{Header=$"{group.Item2} ({zone.Entities.Count(x=>x.Kind==group.Item1)})"};foreach(var e in zone.Entities.Where(x=>x.Kind==group.Item1).OrderBy(x=>x.Name)){var item=new System.Windows.Controls.TreeViewItem{Header=e.Name,Tag=e.Id};item.Selected+=(_,args)=>{if(_session?.ActiveZone is not{} active||!active.Contains(e.Id))return;_selectedId=e.Id;ShowInspector(active.Get(e.Id));_ = ScriptAsync($"window.ddvwf?.selectId?.('{e.Id}')");args.Handled=true;};branch.Items.Add(item);}root.Items.Add(branch);}AssetTree.Items.Add(root);}
 async void ObjectList_SelectionChanged(object sender,System.Windows.Controls.SelectionChangedEventArgs e){if(ObjectList.SelectedItem is not System.Windows.Controls.ListBoxItem item||item.Tag is not Guid id||_session?.ActiveZone is not{} zone||!zone.Contains(id))return;_selectedId=id;ShowInspector(zone.Get(id));await ScriptAsync($"window.ddvwf?.selectId?.('{id}')");}
 async Task RenderModelViewerAsync(ZoneEntity entity){try{if(_client is null||ModelViewer.CoreWebView2 is null)return;if(entity.ClientAsset is null||!_client.RenderMeshes.ContainsKey(entity.ClientAsset)){_modelViewerAsset=null;await ModelViewer.CoreWebView2.ExecuteScriptAsync("window.ddvwf?.loadScene?.('{\\\"zone\\\":\\\"viewer\\\",\\\"meshes\\\":[],\\\"markers\\\":[],\\\"textures\\\":{}}')");StatusText.Text=$"Model Viewer: no resolved Sage render asset for {entity.Name}";return;}_modelViewerAsset=entity.ClientAsset;var z=new CompleteZone{ShortName="viewer"};z.Add(entity with{Position=new EqPosition(0,0,0,0),Rotation=new EqRotation(0,0,0),Scale=1f});var payload=BabylonSceneSerializer.Serialize(z,_client.RenderMeshes,_client.TextureFiles);await ModelViewer.CoreWebView2.ExecuteScriptAsync($"window.ddvwf.loadScene({System.Text.Json.JsonSerializer.Serialize(payload)});window.ddvwf.selectId('{entity.Id}');window.ddvwf.focus();");if(_settings.ModelCameras.TryGetValue(entity.ClientAsset,out var camera)){var cameraJson=System.Text.Json.JsonSerializer.Serialize(new{x=camera.X,y=camera.Y,z=camera.Z,yaw=camera.Yaw,pitch=camera.Pitch,speed=camera.Speed});await ModelViewer.CoreWebView2.ExecuteScriptAsync($"window.ddvwf.setCamera({cameraJson})");}}catch(Exception ex){StatusText.Text=$"Model Viewer failed: {ex.Message}";}}
  Task PersistAsync()=>_workspace.SaveAsync(_settings);
 async void ChooseEqRoot_Click(object sender,RoutedEventArgs e){var dialog=new Microsoft.Win32.OpenFolderDialog{Title="Select EverQuest client directory",Multiselect=false};if(dialog.ShowDialog(this)!=true)return;_settings=_settings with{EqRoot=dialog.FolderName,LastZone=null};DiscoverZones();ZoneText.Text="Choose a zone from EQ Asset Browser";StatusText.Text=dialog.FolderName;await PersistAsync();}
 void Compass_Click(object sender,RoutedEventArgs e){if(_compass is not null){_compass.Activate();return;}_compass=new CompassWindow(_settings.Theme);if(_settings.Windows.TryGetValue("Compass",out var w)){_compass.WindowStartupLocation=WindowStartupLocation.Manual;_compass.Left=w.Left;_compass.Top=w.Top;_compass.Width=Math.Max(_compass.MinWidth,w.Width);_compass.Height=Math.Max(_compass.MinHeight,w.Height);if(w.Minimized)_compass.WindowState=System.Windows.WindowState.Minimized;}_compass.SetHeading(_settings.Camera.Yaw);_compass.Closed+=async(_,_)=>{var c=_compass;if(c is not null){_settings.Windows["Compass"]=new DDVWF.Core.Workspace.WindowState(c.Left,c.Top,c.Width,c.Height,c.WindowState==System.Windows.WindowState.Minimized);_compass=null;await PersistAsync();}};_compass.Show();}
 async void ThemeEditor_Click(object sender,RoutedEventArgs e){var original=_settings.Theme;var w=new ThemeEditorWindow(original,ApplyTheme){Owner=this};if(w.ShowDialog()==true){_settings=_settings with{Theme=w.Settings};ApplyTheme(w.Settings);await PersistAsync();}else ApplyTheme(original);}
 async void Shortcuts_Click(object sender,RoutedEventArgs e){var w=new ShortcutEditorWindow(_settings.Shortcuts,_settings.Theme,changed=>{_settings=_settings with{Shortcuts=new Dictionary<string,string>(changed,StringComparer.OrdinalIgnoreCase)};_ = PersistAsync();StatusText.Text="Shortcuts saved";}){Owner=this};w.ShowDialog();}
 void ApplyTheme(ThemeSettings theme){try{var palette=ThemeSettings.DefaultPalette();foreach(var p in theme.Palette)palette[p.Key]=p.Value;foreach(var p in palette)Resources[p.Key]=new System.Windows.Media.SolidColorBrush((System.Windows.Media.Color)System.Windows.Media.ColorConverter.ConvertFromString(p.Value));Foreground=(System.Windows.Media.Brush)Resources["TextBrush"];Background=(System.Windows.Media.Brush)Resources["ViewportBrush"];SceneTree.Foreground=(System.Windows.Media.Brush)Resources["TextBrush"];SceneTree.Background=(System.Windows.Media.Brush)Resources["PanelBrush"];AssetTree.Foreground=(System.Windows.Media.Brush)Resources["ListTextBrush"];AssetTree.Background=(System.Windows.Media.Brush)Resources["PanelBrush"];ObjectList.Foreground=(System.Windows.Media.Brush)Resources["ListTextBrush"];ObjectList.Background=(System.Windows.Media.Brush)Resources["ModelLibraryBackgroundBrush"];TextureList.Foreground=(System.Windows.Media.Brush)Resources["ListTextBrush"];TextureList.Background=(System.Windows.Media.Brush)Resources["PanelBrush"];MaterialList.Foreground=(System.Windows.Media.Brush)Resources["ListTextBrush"];MaterialList.Background=(System.Windows.Media.Brush)Resources["PanelBrush"];_compass?.ApplyTheme(theme);if(Viewport.CoreWebView2 is not null)_=Viewport.CoreWebView2.ExecuteScriptAsync($"window.ddvwf?.setBackground?.({System.Text.Json.JsonSerializer.Serialize(palette["ViewportBrush"])})");if(ModelViewer.CoreWebView2 is not null)_=ModelViewer.CoreWebView2.ExecuteScriptAsync($"window.ddvwf?.setBackground?.({System.Text.Json.JsonSerializer.Serialize(palette["ModelPreviewBackgroundBrush"])})");}catch(Exception ex){StatusText.Text=$"Theme apply failed: {ex.Message}";}}
 async void ReloadZone_Click(object sender,RoutedEventArgs e){if(_session?.ActiveZone is not{} z)return;await OpenZoneAsync(z.ShortName);}
 void About_Click(object sender,RoutedEventArgs e){MessageBox.Show(this,"Dragon's Den Visual WorldForge\nComplete Zone IR integration build","DDVWF");}
 async void ServerSettings_Click(object sender,RoutedEventArgs e){var w=new ServerSettingsWindow(_settings.Server,_settings.Theme){Owner=this};DdvwfChrome.AttachPersistentGeometry(w,"server-settings");if(w.ShowDialog()!=true)return;_settings=_settings with{Server=w.Settings};await PersistAsync();StatusText.Text="EQEmu SQL settings saved. Reload the zone to apply.";}
 void OpenZone_Click(object sender,RoutedEventArgs e){if(string.IsNullOrWhiteSpace(_settings.EqRoot)||!Directory.Exists(_settings.EqRoot)){StatusText.Text="Configure a valid EverQuest directory before opening a zone.";return;}DiscoverZones();StatusText.Text="Double-click a zone in EQ Asset Browser.";}
 async void CloseZone_Click(object sender,RoutedEventArgs e){_session?.Close();_selectedId=null;SceneTree.Items.Clear();AssetTree.Items.Clear();ObjectList.Items.Clear();TextureList.Items.Clear();MaterialList.Items.Clear();InspectorPanel.Children.Clear();ZoneText.Text="No zone loaded";await ScriptAsync("window.ddvwf?.loadScene?.('{\"zone\":\"\",\"meshes\":[],\"markers\":[],\"textures\":{}}')");if(ModelViewer.CoreWebView2 is not null)await ModelViewer.CoreWebView2.ExecuteScriptAsync("window.ddvwf?.loadScene?.('{\"zone\":\"\",\"meshes\":[],\"markers\":[],\"textures\":{}}')");StatusText.Text="Zone closed";}
 async Task ScriptAsync(string script){if(Viewport.CoreWebView2 is not null)await Viewport.CoreWebView2.ExecuteScriptAsync(script);}
 async void SelectMode_Click(object sender,RoutedEventArgs e)=>await ScriptAsync("window.ddvwf?.setMode?.('select')");
 async void MoveMode_Click(object sender,RoutedEventArgs e)=>await ScriptAsync("window.ddvwf?.setMode?.('move')");
 async void RotateMode_Click(object sender,RoutedEventArgs e)=>await ScriptAsync("window.ddvwf?.setMode?.('rotate')");
 async void ScaleMode_Click(object sender,RoutedEventArgs e)=>await ScriptAsync("window.ddvwf?.setMode?.('scale')");
 async void Focus_Click(object sender,RoutedEventArgs e)=>await ScriptAsync("window.ddvwf?.focus?.()");
 async void Delete_Click(object sender,RoutedEventArgs e){if(_selectedId is not Guid id||_session?.ActiveZone is not{} z)return;_history.Execute(new DeleteEntityCommand(z,id));await ScriptAsync($"window.ddvwf?.remove?.('{id}\')");_selectedId=null;PopulateAssetViewers(z);InspectorPanel.Children.Clear();StatusText.Text="Deleted entity";}
 async void Duplicate_Click(object sender,RoutedEventArgs e){if(_selectedId is not Guid id||_session?.ActiveZone is not{} z)return;var source=z.Get(id);if(source.ServerId is not null){StatusText.Text="Server-backed entities are not duplicated until write-back semantics are enabled.";return;}var p=source.Position;var command=new DuplicateEntityCommand(z,id,new EqPosition(p.X+2,p.Y,p.Z,p.Heading));_history.Execute(command);_selectedId=command.NewId;await RenderActiveAsync();await ScriptAsync($"window.ddvwf?.selectId?.('{command.NewId}')");ShowInspector(z.Get(command.NewId));}
 async void Stamp_Click(object sender,RoutedEventArgs e){if(_selectedId is not Guid id||_session?.ActiveZone is not{} z)return;var source=z.Get(id);if(source.ServerId is not null){StatusText.Text="Server-backed entities cannot be stamped until database write-back is enabled.";return;}var cam=_settings.Camera;var command=new DuplicateEntityCommand(z,id,new EqPosition(cam.X,cam.Y,cam.Z,source.Position.Heading));_history.Execute(command);_selectedId=command.NewId;await RenderActiveAsync();await ScriptAsync($"window.ddvwf?.selectId?.('{command.NewId}')");ShowInspector(z.Get(command.NewId));StatusText.Text=$"Stamped {source.Name} at camera position";}
 async Task RenderActiveAsync(){if(_session?.ActiveZone is not{} zone||_client is null)return;var payload=BabylonSceneSerializer.Serialize(zone,_client.RenderMeshes,_client.TextureFiles);await ScriptAsync($"window.ddvwf.loadScene({System.Text.Json.JsonSerializer.Serialize(payload)})");PopulateAssetViewers(zone);if(_selectedId is Guid id&&zone.Contains(id)){await ScriptAsync($"window.ddvwf?.selectId?.(\'{id}\')");ShowInspector(zone.Get(id));}else _selectedId=null;}
 async void Undo_Click(object sender,RoutedEventArgs e){if(_history.Undo()){await RenderActiveAsync();StatusText.Text="Undo";}}
 async void Redo_Click(object sender,RoutedEventArgs e){if(_history.Redo()){await RenderActiveAsync();StatusText.Text="Redo";}}
 void Exit_Click(object sender,RoutedEventArgs e)=>Close();
}
