using System.Numerics;using DDVWF.Core.Zone;using DDVWF.Renderer.Babylon;
namespace DDVWF.Core.Tests;
public sealed class BabylonSceneSerializerTests
{
 [Fact]public void Serializer_emits_only_resolved_render_assets(){var z=new CompleteZone{ShortName="z"};var id=Guid.NewGuid();z.Add(new(id,ZoneEntityKind.WorldGeometry,"m",new(1,2,3),1,null,"w#m"));z.Add(new(Guid.NewGuid(),ZoneEntityKind.StaticObject,"missing",new(),1,null,"missing"));var asset=new RenderMesh("m",[new("p",[new(new(1,2,3),Vector3.UnitY,Vector2.Zero)],[0],"t.dds",false)],true);var json=BabylonSceneSerializer.Serialize(z,new Dictionary<string,RenderMesh>{{"w#m",asset}});Assert.Contains(id.ToString(),json);Assert.DoesNotContain("missing",json);Assert.Contains("t.dds",json);}
 [Fact]public void Serializer_preserves_full_object_rotation(){var z=new CompleteZone{ShortName="z"};z.Add(new(Guid.NewGuid(),ZoneEntityKind.StaticObject,"o",new(1,2,3,90),1,null,"o",null,new EqRotation(0,90,45)));var asset=new RenderMesh("o",[new("p",[new(Vector3.Zero,Vector3.UnitY,Vector2.Zero)],[0],null,false)],false);var json=BabylonSceneSerializer.Serialize(z,new Dictionary<string,RenderMesh>{{"o",asset}});Assert.Contains("\"rotation\":{\"x\":0,\"y\":90,\"z\":45}",json);}
 [Fact]public void Serializer_keeps_spawns_and_regions_nonvisual_but_marks_unresolved_database_npcs(){var z=new CompleteZone{ShortName="z"};z.Add(new(Guid.NewGuid(),ZoneEntityKind.Spawn,"spawn-marker-must-not-render",new(),400,null,null));z.Add(new(Guid.NewGuid(),ZoneEntityKind.Npc,"npc-marker-must-not-render",new(),6,null,null));z.Add(new(Guid.NewGuid(),ZoneEntityKind.Region,"region-marker-must-not-render",new(),1,null,null));var json=BabylonSceneSerializer.Serialize(z,new Dictionary<string,RenderMesh>());Assert.DoesNotContain("spawn-marker-must-not-render",json);Assert.Contains("npc-marker-must-not-render",json);Assert.DoesNotContain("region-marker-must-not-render",json);}
 [Fact]public void Serializer_carries_Sage_material_modes_to_Babylon_payload(){var z=new CompleteZone{ShortName="z"};var id=Guid.NewGuid();z.Add(new(id,ZoneEntityKind.WorldGeometry,"m",new(),1,null,"w#m"));var mat=new RenderMaterial("add",null,"TransparentAdditiveUnlit",1,false,true,true,Array.Empty<string>(),AlphaBlend:true);var asset=new RenderMesh("m",[new("p",[new(Vector3.Zero,Vector3.UnitY,Vector2.Zero)],[0],null,false,mat)],true);var json=BabylonSceneSerializer.Serialize(z,new Dictionary<string,RenderMesh>{{"w#m",asset}});Assert.Contains("\"additive\":true",json);Assert.Contains("\"unlit\":true",json);Assert.Contains("\"alphaBlend\":true",json);Assert.Contains("\"flipRootX\":true",json);}

 [Fact]public void Shell_scope_emits_world_and_lights_without_population_markers_or_objects(){var z=new CompleteZone{ShortName="z"};var worldId=Guid.NewGuid();z.Add(new(worldId,ZoneEntityKind.WorldGeometry,"world",new(),1,null,"world"));z.Add(new(Guid.NewGuid(),ZoneEntityKind.StaticObject,"object",new(),1,null,"object"));z.Add(new(Guid.NewGuid(),ZoneEntityKind.Npc,"pill",new(),1,1,null));z.Add(new(Guid.NewGuid(),ZoneEntityKind.Light,"light",new(),1,null,null,new LightEntityData(10,0,0,0,new[]{new LightFrame(1,1,1,1)})));var prim=new RenderPrimitive("p",new[]{new RenderVertex(Vector3.Zero,Vector3.UnitY,Vector2.Zero)},new ushort[]{0},null,false);var assets=new Dictionary<string,RenderMesh>{{"world",new("world",new[]{prim},true)},{"object",new("object",new[]{prim},false)}};var json=BabylonSceneSerializer.Serialize(z,assets,null,shellOnly:true);Assert.Contains(worldId.ToString(),json);Assert.Contains("\"light\"",json);Assert.DoesNotContain("\"object\"",json);Assert.DoesNotContain("\"pill\"",json);}
}
