using System.Security.Cryptography;using System.Text;using DDVWF.Core.Zone;using DDVWF.Sage.Pfs;using DDVWF.Sage.Wld;
namespace DDVWF.Sage;
public sealed class SageClientZoneProvider:IClientRenderAssetProvider,IClientAssetResolver,INpcClientAssetResolver
{
 readonly Dictionary<string,RenderMesh> _renderMeshes=new(StringComparer.OrdinalIgnoreCase);readonly Dictionary<string,byte[]> _textureFiles=new(StringComparer.OrdinalIgnoreCase);readonly Dictionary<string,byte[]> _rawTextures=new(StringComparer.OrdinalIgnoreCase);readonly Dictionary<string,string> _nativeAssets=new(StringComparer.OrdinalIgnoreCase);
 public IReadOnlyDictionary<string,RenderMesh> RenderMeshes=>_renderMeshes;public IReadOnlyDictionary<string,byte[]> TextureFiles=>_textureFiles;
 public async Task PopulateAsync(CompleteZone zone,string eqRoot,CancellationToken ct)
 {
  if(string.IsNullOrWhiteSpace(eqRoot)||!Directory.Exists(eqRoot))throw new DirectoryNotFoundException(eqRoot);
  _renderMeshes.Clear();_textureFiles.Clear();_rawTextures.Clear();_nativeAssets.Clear();
  var mainName=zone.ShortName+".s3d";var mainPath=Path.Combine(eqRoot,mainName);if(!File.Exists(mainPath))throw new FileNotFoundException($"Native zone archive '{mainName}' was not found in the configured EQ root.",mainPath);var zoneArchives=Directory.EnumerateFiles(eqRoot,"*",SearchOption.TopDirectoryOnly).Where(p=>{var n=Path.GetFileName(p);return n.StartsWith(zone.ShortName+"_",StringComparison.OrdinalIgnoreCase)||n.StartsWith(zone.ShortName+".",StringComparison.OrdinalIgnoreCase);}).OrderBy(p=>Path.GetFileName(p).Equals(mainName,StringComparison.OrdinalIgnoreCase)?1:0).ThenBy(p=>Path.GetFileName(p),StringComparer.OrdinalIgnoreCase).ToArray();if(zoneArchives.Length==0)throw new FileNotFoundException($"No native zone dependency files were found for zone '{zone.ShortName}' in the configured EQ root.");var globalArchives=Directory.EnumerateFiles(eqRoot,"global*.s3d",SearchOption.TopDirectoryOnly).Where(p=>{var n=Path.GetFileNameWithoutExtension(p);return System.Text.RegularExpressions.Regex.IsMatch(n,@"^global(?:\d+)?_chr$",System.Text.RegularExpressions.RegexOptions.IgnoreCase)||n.Contains("global_obj",StringComparison.OrdinalIgnoreCase);}).OrderBy(p=>Path.GetFileName(p),StringComparer.OrdinalIgnoreCase).ToArray();var archives=globalArchives.Concat(zoneArchives).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
  var objectAssets=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);var objectKinds=new Dictionary<string,ZoneEntityKind>(StringComparer.OrdinalIgnoreCase);
  var placements=new List<(string Wld,SageActorInstance Actor,int Ordinal)>();
  foreach(var archivePath in archives){ct.ThrowIfCancellationRequested();if(!Path.GetExtension(archivePath).Equals(".s3d",StringComparison.OrdinalIgnoreCase))continue;var isGlobal=globalArchives.Contains(archivePath,StringComparer.OrdinalIgnoreCase);var archive=PfsArchive.Open(await File.ReadAllBytesAsync(archivePath,ct));foreach(var tf in archive.Files.Where(x=>x.Key.EndsWith(".dds",StringComparison.OrdinalIgnoreCase)||x.Key.EndsWith(".bmp",StringComparison.OrdinalIgnoreCase)))_rawTextures.TryAdd(tf.Key,tf.Value);
   foreach(var pair in archive.Files.Where(x=>x.Key.EndsWith(".wld",StringComparison.OrdinalIgnoreCase))){WldDocument doc;try{doc=WldDocument.Parse(pair.Value,pair.Key);}catch(Exception ex){throw new InvalidDataException($"Sage WLD parse failed in {Path.GetFileName(archivePath)} / {pair.Key}: {ex.Message}",ex);}try{
    if(!isGlobal&&doc.Kind==WldKind.Zone&&string.Equals(pair.Key,zone.ShortName+".wld",StringComparison.OrdinalIgnoreCase)){var scene=SageSceneBuilder.Build(doc,pair.Value) with{FlipRootX=true};RegisterScene(pair.Key,scene);var ordinal=0;foreach(var mesh in scene.Meshes.Where(x=>x.Primitives.Count>0)){var key=$"{pair.Key}#{mesh.Name}";zone.Add(new(Stable(zone.ShortName,pair.Key,"world",mesh.Name,ordinal++),ZoneEntityKind.WorldGeometry,mesh.Name,new(0,0,0),1,null,key));}var regionOrdinal=0;var regions=doc.Fragments.Where(x=>x.KnownType==WldFragmentType.BspRegion).Select((x,i)=>WldBspReader.ReadRegion(i,x,pair.Value)).ToArray();foreach(var rt in doc.Fragments.Where(x=>x.KnownType==WldFragmentType.RegionType)){var t=WldBspReader.ReadType(doc,rt,pair.Value);foreach(var ri in t.RegionIndices.Where(i=>i>=0&&i<regions.Length)){var r=regions[ri];zone.Add(new(Stable(zone.ShortName,pair.Key,"region",ri,t.Tag),ZoneEntityKind.Region,$"{t.Tag} [{ri}]",new(0,0,0),1,null,null,t.Data));regionOrdinal++;}}}
    if(doc.Kind is WldKind.Objects or WldKind.Characters or WldKind.Equipment){var scene=SageSceneBuilder.Build(doc,pair.Value);var assetScope=doc.Kind==WldKind.Objects?"object":doc.Kind==WldKind.Characters?"character":"equipment";RegisterScene(pair.Key,scene,assetScope);foreach(var af in doc.Fragments.Where(x=>x.KnownType==WldFragmentType.ActorDefinition)){var ad=WldActorDefinitionReader.Read(doc,af,pair.Value);if(ad.ResolvedModelFragment is not int mi||mi<0||mi>=doc.Fragments.Count)continue;var actorName=ad.Name.Replace("_ACTORDEF","",StringComparison.OrdinalIgnoreCase).ToLowerInvariant();if(string.IsNullOrWhiteSpace(actorName))continue;if(ad.Type==SageActorType.Static){var meshName=doc.Fragments[mi].Name;var key=$"{pair.Key}#{assetScope}#{meshName}";if(_renderMeshes.ContainsKey(key)){objectAssets[actorName]=key;_nativeAssets[actorName]=key;objectKinds[actorName]=ZoneEntityKind.StaticObject;}}else if(ad.Type==SageActorType.Skeletal&&doc.Fragments[mi].KnownType==WldFragmentType.SkeletonHierarchy){var skeleton=WldSkeletonReader.Read(doc,doc.Fragments[mi],pair.Value);var skinned=SageSkinnedSceneBuilder.Build(doc,pair.Value,skeleton,actorName);if(skinned is not null){skinned=ProcessSkinnedTextures(skinned);var key=$"{pair.Key}#skeletal#{actorName}";_renderMeshes[key]=skinned;objectAssets[actorName]=key;_nativeAssets[actorName]=key;objectKinds[actorName]=ZoneEntityKind.AnimatedObject;}}}}
    if(!isGlobal&&doc.Kind==WldKind.Lights){var sources=new Dictionary<int,SageLightSource>();for(var li=0;li<doc.Fragments.Count;li++)if(doc.Fragments[li].KnownType==WldFragmentType.LightSource)sources[li]=WldLightReader.ReadSource(doc.Fragments[li],pair.Value);var ordinal=0;foreach(var gf in doc.Fragments.Where(x=>x.KnownType==WldFragmentType.GlobalAmbientLight)){var g=WldLightReader.ReadGlobalAmbient(gf,pair.Value);var frames=new[]{new LightFrame(1f,g.Red/255f,g.Green/255f,g.Blue/255f)};zone.Add(new(Stable(zone.ShortName,pair.Key,"global-ambient",ordinal++),ZoneEntityKind.Light,string.IsNullOrWhiteSpace(gf.Name)?"Global Ambient":gf.Name,new(0,0,0),1,null,null,new LightEntityData(0,0,0,0,frames,true)));}foreach(var lf in doc.Fragments.Where(x=>x.KnownType==WldFragmentType.LightInstance)){var light=WldLightReader.ReadInstance(lf,pair.Value);var refIndex=light.ReferenceIndex;if(refIndex>=0&&refIndex<doc.Fragments.Count&&doc.Fragments[refIndex].KnownType==WldFragmentType.LightSourceReference)refIndex=WldMaterialReader.ReadReference(doc.Fragments[refIndex],pair.Value);var name=refIndex>=0&&refIndex<doc.Fragments.Count?doc.Fragments[refIndex].Name:lf.Name;sources.TryGetValue(refIndex,out var source);var frameCount=Math.Max(1,source is null?0:checked((int)source.FrameCount));var frames=Enumerable.Range(0,frameCount).Select(i=>{var level=source is not null&&i<source.Levels.Count?source.Levels[i]:1f;var color=source is not null&&i<source.Colors.Count?source.Colors[i]:new System.Numerics.Vector3(1,1,1);return new LightFrame(level,color.X,color.Y,color.Z);}).ToArray();var data=new LightEntityData(light.Radius,source?.Flags??0,source?.CurrentFrame??0,source?.Sleep??0,frames);zone.Add(new(Stable(zone.ShortName,pair.Key,"light",ordinal++),ZoneEntityKind.Light,name,new(light.Position.X,light.Position.Y,light.Position.Z),Math.Max(.01f,light.Radius),null,null,data));}}
    if(!isGlobal&&doc.Kind==WldKind.ZoneObjects){var ordinal=0;foreach(var fragment in doc.Fragments.Where(x=>x.KnownType==WldFragmentType.ActorInstance)){var actor=WldActorReader.ReadActorInstance(doc,fragment,pair.Value);if(actor.Location is not null)placements.Add((pair.Key,actor,ordinal++));}}
    }catch(Exception ex){throw new InvalidDataException($"Sage WLD build failed in {Path.GetFileName(archivePath)} / {pair.Key} ({doc.Kind}): {ex.Message}",ex);}
   }
  }
  foreach(var p in placements){var loc=p.Actor.Location!.Value;objectAssets.TryGetValue(p.Actor.ObjectName,out var asset);var kind=objectKinds.TryGetValue(p.Actor.ObjectName,out var k)?k:ZoneEntityKind.StaticObject;zone.Add(new(Stable(zone.ShortName,p.Wld,"actor",p.Actor.ObjectName,p.Ordinal),kind,p.Actor.ObjectName,new(loc.X,loc.Y,loc.Z,loc.RotateY+180f),p.Actor.ScaleFactor==0?1:p.Actor.ScaleFactor,null,asset,new ActorEntityData(p.Actor.BoundingRadius,p.Actor.SoundName,p.Actor.VertexColorReference,p.Actor.UserData),new EqRotation(loc.RotateX,loc.RotateY+180f,loc.RotateZ)));}
 }
 void RegisterScene(string wld,SageSceneDocument scene,string? scope=null)
 {
  foreach(var sm in scene.Meshes.Where(x=>x.Primitives.Count>0)){
   var key=scope is null?$"{wld}#{sm.Name}":$"{wld}#{scope}#{sm.Name}";
   var rp=sm.Primitives.Select(p=>{var m=scene.Materials[p.MaterialIndex];var processed=m.Frames.Select(x=>ProcessedTexture(x.FileName,m.Shader)).Where(x=>x is not null).Cast<string>().ToArray();var tex=processed.FirstOrDefault();var alpha=m.Shader switch{SageShaderType.Transparent25=>.25f,SageShaderType.Transparent50 or SageShaderType.TransparentSkydome=>.5f,SageShaderType.Transparent75 or SageShaderType.TransparentAdditive or SageShaderType.TransparentAdditiveUnlit=>.75f,_=>1f};var mat=new RenderMaterial(m.Name,tex,m.Shader.ToString(),alpha,m.Shader==SageShaderType.TransparentMasked,m.Shader is SageShaderType.TransparentAdditive or SageShaderType.TransparentAdditiveUnlit or SageShaderType.TransparentAdditiveUnlitSkydome,m.Shader is SageShaderType.TransparentAdditiveUnlit or SageShaderType.TransparentAdditiveUnlitSkydome,processed,m.AnimationDelayMs);var morph=p.MorphFrames?.Select(frame=>new RenderMorphFrame(frame.PositionDeltas,frame.DelayMs)).ToArray();return new RenderPrimitive(p.Name,p.Vertices.Select(v=>new RenderVertex(v.Position,v.Normal,v.Uv,v.SourceIndex,0,v.Color)).ToArray(),p.Indices,tex,p.PassThrough,mat,morph);}).ToArray();
   _renderMeshes[key]=new(sm.Name,rp,scene.FlipRootX);
  }
 }
 RenderMesh ProcessSkinnedTextures(RenderMesh mesh){var prims=mesh.Primitives.Select(p=>{if(p.Material is not{} m||!Enum.TryParse<SageShaderType>(m.Shader,out var shader))return p;var nativeFrames=m.TextureFrames??Array.Empty<string>();var frames=nativeFrames.Select(x=>ProcessedTexture(x,shader)).Where(x=>x is not null).Cast<string>().ToArray();var tex=frames.FirstOrDefault();return p with{TextureName=tex,Material=m with{TextureName=tex,TextureFrames=frames}};}).ToArray();return mesh with{Primitives=prims};}
  string? ProcessedTexture(string native,SageShaderType shader){if(!_rawTextures.TryGetValue(native,out var bytes))return null;var key=$"{Path.GetFileNameWithoutExtension(native).ToLowerInvariant()}-{(int)shader}.png";if(!_textureFiles.ContainsKey(key))_textureFiles[key]=SageTextureProcessor.Process(native,bytes,shader);return key;}
  static readonly Lazy<Dictionary<int,Dictionary<int,string>>> RaceModels=new(()=>{
   using var stream=typeof(SageClientZoneProvider).Assembly.GetManifestResourceStream("DDVWF.Sage.Authority.raceData.json")??throw new InvalidDataException("Pinned Sage raceData.json resource is missing.");
   using var doc=System.Text.Json.JsonDocument.Parse(stream);var result=new Dictionary<int,Dictionary<int,string>>();
   foreach(var row in doc.RootElement.EnumerateArray()){if(!row.TryGetProperty("id",out var idNode)||!idNode.TryGetInt32(out var id))continue;var genders=new Dictionary<int,string>();for(var g=0;g<=2;g++)if(row.TryGetProperty(g.ToString(),out var value)){var model=value.GetString();if(!string.IsNullOrWhiteSpace(model))genders[g]=model.ToLowerInvariant();}result[id]=genders;}return result;
  });
  public string? ResolveClientAsset(string nativeReference){var key=Path.GetFileNameWithoutExtension(nativeReference).Replace("_ACTORDEF","",StringComparison.OrdinalIgnoreCase).ToLowerInvariant();return _nativeAssets.TryGetValue(key,out var asset)?asset:null;}
  public string? ResolveNpcAsset(int race,int gender,int modelOverride=0){var effectiveRace=modelOverride>0?modelOverride:race;if(!RaceModels.Value.TryGetValue(effectiveRace,out var models))return _nativeAssets.TryGetValue("hum",out var hum)?hum:null;var model=models.TryGetValue(gender,out var exact)?exact:models.TryGetValue(2,out var neutral)?neutral:"hum";return _nativeAssets.TryGetValue(model,out var asset)?asset:null;}
  public static Guid Stable(params object[] parts){var text=string.Join("|",parts.Select(x=>x?.ToString()??""));return new Guid(MD5.HashData(Encoding.UTF8.GetBytes(text)));}
}