using System.Security.Cryptography;using System.Text;using DDVWF.Core.Zone;using DDVWF.Sage.Pfs;using DDVWF.Sage.Wld;
namespace DDVWF.Sage;
public sealed class SageClientZoneProvider:IClientRenderAssetProvider
{
 readonly Dictionary<string,RenderMesh> _renderMeshes=new(StringComparer.OrdinalIgnoreCase);readonly Dictionary<string,byte[]> _textureFiles=new(StringComparer.OrdinalIgnoreCase);
 public IReadOnlyDictionary<string,RenderMesh> RenderMeshes=>_renderMeshes;public IReadOnlyDictionary<string,byte[]> TextureFiles=>_textureFiles;
 public async Task PopulateAsync(CompleteZone zone,string eqRoot,CancellationToken ct)
 {
  if(string.IsNullOrWhiteSpace(eqRoot)||!Directory.Exists(eqRoot))throw new DirectoryNotFoundException(eqRoot);
  _renderMeshes.Clear();_textureFiles.Clear();
  var paths=new[]{Path.Combine(eqRoot,zone.ShortName+".s3d"),Path.Combine(eqRoot,zone.ShortName+"_obj.s3d"),Path.Combine(eqRoot,zone.ShortName+"_obj2.s3d")};
  var archives=paths.Where(File.Exists).ToArray();if(archives.Length==0)throw new FileNotFoundException($"No native S3D archive was found for zone '{zone.ShortName}' in the configured EQ root.");
  var objectAssets=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);
  var placements=new List<(string Wld,SageActorInstance Actor,int Ordinal)>();
  foreach(var archivePath in archives){ct.ThrowIfCancellationRequested();var archive=PfsArchive.Open(await File.ReadAllBytesAsync(archivePath,ct));foreach(var tf in archive.Files.Where(x=>x.Key.EndsWith(".dds",StringComparison.OrdinalIgnoreCase)||x.Key.EndsWith(".bmp",StringComparison.OrdinalIgnoreCase)))_textureFiles.TryAdd(tf.Key,tf.Value);
   foreach(var pair in archive.Files.Where(x=>x.Key.EndsWith(".wld",StringComparison.OrdinalIgnoreCase))){var doc=WldDocument.Parse(pair.Value,pair.Key);
    if(doc.Kind==WldKind.Zone){var scene=SageSceneBuilder.Build(doc,pair.Value);RegisterScene(pair.Key,scene);var ordinal=0;foreach(var mesh in scene.Meshes.Where(x=>x.Primitives.Count>0)){var key=$"{pair.Key}#{mesh.Name}";zone.Add(new(Stable(zone.ShortName,pair.Key,"world",mesh.Name,ordinal++),ZoneEntityKind.WorldGeometry,mesh.Name,new(0,0,0),1,null,key));}var regionOrdinal=0;var regions=doc.Fragments.Where(x=>x.KnownType==WldFragmentType.BspRegion).Select((x,i)=>WldBspReader.ReadRegion(i,x,pair.Value)).ToArray();foreach(var rt in doc.Fragments.Where(x=>x.KnownType==WldFragmentType.RegionType)){var t=WldBspReader.ReadType(doc,rt,pair.Value);foreach(var ri in t.RegionIndices.Where(i=>i>=0&&i<regions.Length)){var r=regions[ri];zone.Add(new(Stable(zone.ShortName,pair.Key,"region",ri,t.Tag),ZoneEntityKind.Region,$"{t.Tag} [{ri}]",new(0,0,0),1,null,null));regionOrdinal++;}}}
    if(doc.Kind==WldKind.Objects){var scene=SageSceneBuilder.Build(doc,pair.Value);RegisterScene(pair.Key,scene,"object");foreach(var af in doc.Fragments.Where(x=>x.KnownType==WldFragmentType.ActorDefinition)){var ad=WldActorDefinitionReader.Read(doc,af,pair.Value);if(ad.Type!=SageActorType.Static||ad.ResolvedModelFragment is not int mi||mi<0||mi>=doc.Fragments.Count)continue;var meshName=doc.Fragments[mi].Name;var key=$"{pair.Key}#object#{meshName}";if(_renderMeshes.ContainsKey(key)){var actorName=ad.Name.Replace("_ACTORDEF","",StringComparison.OrdinalIgnoreCase).ToLowerInvariant();if(!string.IsNullOrWhiteSpace(actorName))objectAssets[actorName]=key;}}}
    if(doc.Kind==WldKind.Lights){var sources=new Dictionary<int,SageLightSource>();for(var li=0;li<doc.Fragments.Count;li++)if(doc.Fragments[li].KnownType==WldFragmentType.LightSource)sources[li]=WldLightReader.ReadSource(doc.Fragments[li],pair.Value);var ordinal=0;foreach(var lf in doc.Fragments.Where(x=>x.KnownType==WldFragmentType.LightInstance)){var light=WldLightReader.ReadInstance(lf,pair.Value);var refIndex=light.ReferenceIndex;if(refIndex>=0&&refIndex<doc.Fragments.Count&&doc.Fragments[refIndex].KnownType==WldFragmentType.LightSourceReference)refIndex=WldMaterialReader.ReadReference(doc.Fragments[refIndex],pair.Value);var name=refIndex>=0&&refIndex<doc.Fragments.Count?doc.Fragments[refIndex].Name:lf.Name;zone.Add(new(Stable(zone.ShortName,pair.Key,"light",ordinal++),ZoneEntityKind.Light,name,new(light.Position.X,light.Position.Y,light.Position.Z),Math.Max(.01f,light.Radius),null,null));}}
    if(doc.Kind==WldKind.ZoneObjects){var ordinal=0;foreach(var fragment in doc.Fragments.Where(x=>x.KnownType==WldFragmentType.ActorInstance)){var actor=WldActorReader.ReadActorInstance(doc,fragment,pair.Value);if(actor.Location is not null)placements.Add((pair.Key,actor,ordinal++));}}
   }
  }
  foreach(var p in placements){var loc=p.Actor.Location!.Value;objectAssets.TryGetValue(p.Actor.ObjectName,out var asset);zone.Add(new(Stable(zone.ShortName,p.Wld,"actor",p.Actor.ObjectName,p.Ordinal),ZoneEntityKind.StaticObject,p.Actor.ObjectName,new(loc.X,loc.Y,loc.Z,loc.RotateY+180f),p.Actor.ScaleFactor==0?1:p.Actor.ScaleFactor,null,asset));}
 }
 void RegisterScene(string wld,SageSceneDocument scene,string? scope=null){foreach(var sm in scene.Meshes.Where(x=>x.Primitives.Count>0)){var key=scope is null?$"{wld}#{sm.Name}":$"{wld}#{scope}#{sm.Name}";var rp=sm.Primitives.Select(p=>{var m=scene.Materials[p.MaterialIndex];var tex=m.Frames.FirstOrDefault()?.FileName;var alpha=m.Shader switch{SageShaderType.Transparent25=>.25f,SageShaderType.Transparent50 or SageShaderType.TransparentSkydome=>.5f,SageShaderType.Transparent75 or SageShaderType.TransparentAdditive or SageShaderType.TransparentAdditiveUnlit=>.75f,_=>1f};var mat=new RenderMaterial(m.Name,tex,m.Shader.ToString(),alpha,m.Shader==SageShaderType.TransparentMasked,m.Shader is SageShaderType.TransparentAdditive or SageShaderType.TransparentAdditiveUnlit or SageShaderType.TransparentAdditiveUnlitSkydome,m.Shader is SageShaderType.TransparentAdditiveUnlit or SageShaderType.TransparentAdditiveUnlitSkydome,m.Frames.Select(x=>x.FileName).ToArray(),m.AnimationDelayMs);var morph=p.MorphFrames?.Select(frame=>new RenderMorphFrame(frame.PositionDeltas,frame.DelayMs)).ToArray();return new RenderPrimitive(p.Name,p.Vertices.Select(v=>new RenderVertex(v.Position,v.Normal,v.Uv,v.SourceIndex)).ToArray(),p.Indices,tex,p.PassThrough,mat,morph);}).ToArray();_renderMeshes[key]=new(sm.Name,rp,scene.FlipRootX);}}
 public static Guid Stable(params object[] parts){var text=string.Join("|",parts.Select(x=>x?.ToString()??""));return new Guid(MD5.HashData(Encoding.UTF8.GetBytes(text)));}
}