using System.IO.Compression;
using System.Numerics;
using System.Text;
namespace DDVWF.Core.Zone;
public sealed class EqEmuCollisionMap
{
 public const float BestZInvalid=-99999f;readonly Vector3[] v;readonly uint[] ix;
 EqEmuCollisionMap(List<Vector3> a,List<uint>b)=>(v,ix)=(a.ToArray(),b.ToArray());
 public static EqEmuCollisionMap Load(string path){using var f=File.OpenRead(path);using var r=new BinaryReader(f,Encoding.UTF8);return r.ReadUInt32() switch{0x01000000=>V1(r),0x02000000=>V2(r),var x=>throw new InvalidDataException($"Unsupported EQEmu map version 0x{x:X8}.")};}
 public float FindBestZ(float x,float y,float z,int heightAdjust=1,float underworld=0,float maxZ=0){var p=new Vector3(x,y,z+heightAdjust);if(Vertical(p,-1,out var d)&&(underworld==0||d>=underworld))return d;if(Vertical(p,1,out var u)&&(maxZ==0||u<=maxZ))return u;return BestZInvalid;}
 bool Vertical(Vector3 p,float dz,float maxDistance,out float z){float near=maxDistance;var hit=false;var d=new Vector3(0,0,dz);for(int i=0;i+2<ix.Length;i+=3)if(Ray(p,d,v[ix[i]],v[ix[i+1]],v[ix[i+2]],out var t)&&t<near){near=t;hit=true;}z=hit?p.Z+dz*near:0;return hit;}
 static bool Ray(Vector3 p,Vector3 d,Vector3 a,Vector3 b,Vector3 c,out float t){var e1=b-a;var e2=c-a;var h=Vector3.Cross(d,e2);var det=Vector3.Dot(e1,h);if(det>-0.00001f&&det<0.00001f){t=0;return false;}var f=1/det;var s=p-a;var u=f*Vector3.Dot(s,h);if(u<0||u>1){t=0;return false;}var q=Vector3.Cross(s,e1);var vv=f*Vector3.Dot(d,q);if(vv<0||u+vv>1){t=0;return false;}t=f*Vector3.Dot(e2,q);return t>0;}
 static EqEmuCollisionMap V1(BinaryReader r){uint n=r.ReadUInt32();_=r.ReadUInt16();_=r.ReadUInt32();var a=new List<Vector3>(checked((int)n*3));var b=new List<uint>(checked((int)n*3));for(uint i=0;i<n;i++){for(int j=0;j<3;j++){a.Add(V(r));b.Add((uint)b.Count);}for(int j=0;j<4;j++)_=r.ReadSingle();}return new(a,b);}
 sealed record P(uint A,uint B,uint C,byte Vis);sealed record M(Vector3[] V,P[] P);
 static EqEmuCollisionMap V2(BinaryReader o){uint ds=o.ReadUInt32(),bs=o.ReadUInt32();var data=o.ReadBytes(checked((int)ds));if(data.Length!=ds)throw new EndOfStreamException();using var input=new MemoryStream(data,false);using var z=new ZLibStream(input,CompressionMode.Decompress);using var mem=new MemoryStream(checked((int)bs));z.CopyTo(mem);if(mem.Length!=bs)throw new InvalidDataException($"EQEmu V2 map inflated to {mem.Length}; expected {bs}.");mem.Position=0;using var r=new BinaryReader(mem,Encoding.UTF8);
  uint vc=r.ReadUInt32(),ic=r.ReadUInt32(),nvc=r.ReadUInt32(),nic=r.ReadUInt32(),mc=r.ReadUInt32(),pc=r.ReadUInt32(),pgc=r.ReadUInt32(),tc=r.ReadUInt32(),qpt=r.ReadUInt32();float upv=r.ReadSingle();var a=new List<Vector3>(checked((int)vc));var b=new List<uint>(checked((int)ic));for(uint i=0;i<vc;i++)a.Add(V(r));for(uint i=0;i<ic;i++)b.Add(r.ReadUInt32());r.BaseStream.Seek(checked((long)nvc*12+(long)nic*4),SeekOrigin.Current);
  var models=new Dictionary<string,M>(StringComparer.Ordinal);for(uint i=0;i<mc;i++){var name=S(r);uint mvc=r.ReadUInt32(),mpc=r.ReadUInt32();var mv=new Vector3[mvc];for(int j=0;j<mv.Length;j++)mv[j]=V(r);var mp=new P[mpc];for(int j=0;j<mp.Length;j++)mp[j]=new(r.ReadUInt32(),r.ReadUInt32(),r.ReadUInt32(),r.ReadByte());models[name]=new(mv,mp);}
  for(uint i=0;i<pc;i++){var name=S(r);var pos=V(r);var rot=V(r);var scale=V(r);if(!models.TryGetValue(name,out var m))continue;foreach(var p in m.P){if(p.Vis==0)continue;Vector3 T(Vector3 x)=>Tr(Sc(Rot(x,rot.X,rot.Y,rot.Z),scale),pos);Add(a,b,T(m.V[p.A]),T(m.V[p.B]),T(m.V[p.C]),true);}}
  const float D=3.14159f/180f;for(uint i=0;i<pgc;i++){var gp=V(r);var gr=V(r);var gs=V(r);var tile=V(r);uint count=r.ReadUInt32();for(uint j=0;j<count;j++){var name=S(r);var lp=V(r);var lr=V(r)*D;var ls=V(r);if(!models.TryGetValue(name,out var m))continue;var corr=Rot(lp,gr.X*D,0,0);foreach(var p in m.P){if(p.Vis==0)continue;Vector3 T(Vector3 x){x=Sc(x,ls);x=Tr(x,lp);x=Rot(x,gr.X*D,0,0);x=Rot(x,0,gr.Y*D,0);x=Tr(x,-corr);x=Rot(x,lr.X,0,0);x=Rot(x,0,-lr.Y,0);x=Rot(x,0,0,lr.Z);x=Tr(x,corr);x=Rot(x,0,0,gr.Z*D);x=Sc(x,gs);x=Tr(x,tile);return Tr(x,gp);}Add(a,b,T(m.V[p.A]),T(m.V[p.B]),T(m.V[p.C]),true);}}}
  uint qc=checked(qpt*qpt),tvc=checked((qpt+1)*(qpt+1));var flags=new byte[qc];var h=new float[tvc];for(uint ti=0;ti<tc;ti++){bool flat=r.ReadBoolean();float x=r.ReadSingle(),y=r.ReadSingle();if(flat){float zz=r.ReadSingle(),span=qpt*upv;uint first=(uint)a.Count;a.Add(new(x,y,zz));a.Add(new(x+span,y,zz));a.Add(new(x+span,y+span,zz));a.Add(new(x,y+span,zz));b.Add(first+3);b.Add(first+1);b.Add(first+2);b.Add(first+3);b.Add(first);b.Add(first+1);continue;}for(int j=0;j<flags.Length;j++)flags[j]=r.ReadByte();for(int j=0;j<h.Length;j++)h[j]=r.ReadSingle();int row=-1;var cache=new Dictionary<Vector3,uint>();for(uint q=0;q<qc;q++){if(q%qpt==0)row++;if((flags[q]&1)!=0)continue;uint col=q%qpt;var p1=new Vector3(x+row*upv,y+col*upv,h[q+(uint)row]);var p2=new Vector3(p1.X+upv,p1.Y,h[q+(uint)row+qpt+1]);var p3=new Vector3(p1.X+upv,p1.Y+upv,h[q+(uint)row+qpt+2]);var p4=new Vector3(p1.X,p1.Y+upv,h[q+(uint)row+1]);uint Id(Vector3 p){if(cache.TryGetValue(p,out var id))return id;id=(uint)a.Count;a.Add(p);cache[p]=id;return id;}uint i1=Id(p1),i2=Id(p2),i3=Id(p3),i4=Id(p4);b.Add(i4);b.Add(i2);b.Add(i3);b.Add(i4);b.Add(i1);b.Add(i2);}}return new(a,b);}
 static Vector3 V(BinaryReader r)=>new(r.ReadSingle(),r.ReadSingle(),r.ReadSingle());static string S(BinaryReader r){var a=new List<byte>();byte x;while((x=r.ReadByte())!=0)a.Add(x);return Encoding.UTF8.GetString(a.ToArray());}
 static Vector3 Rot(Vector3 x,float rx,float ry,float rz){var n=x;n.Y=MathF.Cos(rx)*x.Y-MathF.Sin(rx)*x.Z;n.Z=MathF.Sin(rx)*x.Y+MathF.Cos(rx)*x.Z;x=n;n.X=MathF.Cos(ry)*x.X+MathF.Sin(ry)*x.Z;n.Z=-MathF.Sin(ry)*x.X+MathF.Cos(ry)*x.Z;x=n;n.X=MathF.Cos(rz)*x.X-MathF.Sin(rz)*x.Y;n.Y=MathF.Sin(rz)*x.X+MathF.Cos(rz)*x.Y;return n;}static Vector3 Sc(Vector3 x,Vector3 s)=>new(x.X*s.X,x.Y*s.Y,x.Z*s.Z);static Vector3 Tr(Vector3 x,Vector3 t)=>x+t;
 static void Add(List<Vector3>a,List<uint>b,Vector3 x,Vector3 y,Vector3 z,bool swap){if(swap){x=new(x.Y,x.X,x.Z);y=new(y.Y,y.X,y.Z);z=new(z.Y,z.X,z.Z);}uint i=(uint)a.Count;a.Add(x);a.Add(y);a.Add(z);b.Add(i);b.Add(i+1);b.Add(i+2);}
}
